In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
#Funciones auxiliares sklearn
from sklearn.model_selection import train_test_split, StratifiedKFold #Split y cross Validation
from sklearn.metrics import cohen_kappa_score, accuracy_score, balanced_accuracy_score #Metricas
from sklearn.utils import shuffle 


#Gradient Boosting
import lightgbm as lgb


# Configuramos el estilo de las visualizaciones
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")

breed_df = pd.read_csv(os.path.join(r"C:\Users\fchiavassa\Desktop\Nueva carpeta\Inteligencia Artificial\Codigos\Maestria\breed_labels.csv"))
color_df = pd.read_csv(os.path.join(r"C:\Users\fchiavassa\Desktop\Nueva carpeta\Inteligencia Artificial\Codigos\Maestria\color_labels.csv"))
state_df = pd.read_csv(os.path.join(r"C:\Users\fchiavassa\Desktop\Nueva carpeta\Inteligencia Artificial\Codigos\Maestria\state_labels.csv"))

# Definimos la ruta
ruta_archivo = r"C:\Users\fchiavassa\Desktop\Nueva carpeta\Inteligencia Artificial\Codigos\Maestria\train.csv"

# Intentamos leer con latin-1

# Agregamos el parámetro sep=';'
train_df = pd.read_csv(ruta_archivo, sep=',', encoding='latin-1')

In [18]:
SEED = 42 #Semilla de procesos aleatorios (para poder replicar exactamente al volver a correr un modelo)
TEST_SIZE = 0.2 #Facción para train/test= split

In [19]:
#Separo un 20% para test estratificado opr target
df_train, df_test = train_test_split(train_df,
                               test_size = TEST_SIZE,
                               random_state = SEED,
                               stratify = train_df.AdoptionSpeed)

In [16]:
import pandas as pd

# 1. Cargar el dataset original
# Asegúrate de que el archivo esté en la misma carpeta que tu notebook

def categorizar_tamano(row):
    breed = str(row['BreedName']).lower()
    pet_type = row['Type']
    
    # Gatos (Type = 2): Los clasificamos como 'Pequeño' por defecto en comparación a un perro
    if pet_type == 2:
        return 'Pequeño'
        
    # Perros (Type = 1)
    if 'mixed breed' in breed:
        return 'Mediano' # Promedio estadístico seguro para perros mestizos
        
    # A. Excepciones específicas (se evalúan antes que las reglas generales)
    excepciones_grandes = ['black russian terrier', 'airedale terrier', 'afghan hound', 'bloodhound', 'greyhound', 'irish wolfhound']
    excepciones_medianos = ['american staffordshire terrier', 'pit bull terrier', 'bull terrier', 'beagle', 'basset hound', 'whippet', 'standard schnauzer', 'cocker spaniel']
    excepciones_pequenos = ['dachshund', 'miniature schnauzer', 'toy', 'miniature']
    
    if any(exc in breed for exc in excepciones_grandes):
        return 'Grande'
    if any(exc in breed for exc in excepciones_medianos):
        return 'Mediano'
    if any(exc in breed for exc in excepciones_pequenos):
        return 'Pequeño'
        
    # B. Reglas generales por familias funcionales / palabras clave
    # La mayoría de los terriers y perros de compañía son pequeños
    keywords_pequenos = ['terrier', 'chihuahua', 'pomeranian', 'pug', 'shih tzu', 'maltese', 'pekingese', 'corgi', 'bichon', 'french bulldog', 'papillon', 'havanese', 'pinscher']
    
    # La mayoría de los pastores, cobradores, mastines y sabuesos son grandes
    keywords_grandes = ['retriever', 'shepherd', 'mastiff', 'great', 'husky', 'malamute', 'akita', 'hound', 'pointer', 'setter', 'collie', 'rottweiler', 'doberman', 'boxer', 'american bulldog', 'sheepdog', 'dane', 'bernard', 'pyrenees', 'newfoundland', 'weimaraner', 'ridgeback', 'corso', 'komondor', 'kuvasz', 'borzoi', 'dalmatian']
    
    if any(kw in breed for kw in keywords_pequenos):
        return 'Pequeño'
    if any(kw in breed for kw in keywords_grandes):
        return 'Grande'
        
    # C. Todo lo que no caiga en las reglas anteriores se asume Mediano (ej. Spaniels, Bulldogs ingleses, Spitz)
    return 'Mediano'

# 2. Aplicar la función para crear la nueva columna
breed_df['SizeCategory'] = breed_df.apply(categorizar_tamano, axis=1)

# Unimos indicando que Breed1 equivale a BreedID
df_train = df_train.merge(
    breed_df[['BreedID', 'SizeCategory']], 
    left_on='Breed1', 
    right_on='BreedID', 
    how='left'
)

df_test = df_test.merge(
    breed_df[['BreedID', 'SizeCategory']], 
    left_on='Breed1', 
    right_on='BreedID', 
    how='left'
)

# Opcional: eliminar la columna BreedID duplicada que queda tras el merge
df_train = df_train.drop(columns=['BreedID'])
df_test = df_test.drop(columns=['BreedID'])
# 3. Exportar el resultado a un nuevo archivo CSV
nuevo_archivo = 'PetFinder-BreedLabels-Sized.csv'
breed_df.to_csv(nuevo_archivo, index=False)

print(f"Archivo generado exitosamente: '{nuevo_archivo}'")
print("\nMuestra de cómo quedaron las categorías:")
display(breed_df.sample(10, random_state=42))

Archivo generado exitosamente: 'PetFinder-BreedLabels-Sized.csv'

Muestra de cómo quedaron las categorías:

     BreedID  Type                       BreedName SizeCategory
183      184     1                            Pumi      Mediano
60        61     1             Chinese Crested Dog      Mediano
124      125     1                 Irish Wolfhound       Grande
93        94     1                 Fila Brasileiro      Mediano
63        64     1    Chocolate Labrador Retriever       Grande
9         10     1  American Staffordshire Terrier      Mediano
147      148     1              Manchester Terrier      Pequeño
158      159     1                 Norfolk Terrier      Pequeño
168      169     1                       Pekingese      Pequeño
33        34     1                      Bloodhound       Grande

In [27]:
#Genero dataframes de train y test con sus respectivos targets
X_train = df_train.drop(columns=['AdoptionSpeed','RescuerID'])
y_train = df_train['AdoptionSpeed']

X_test = df_test.drop(columns=['AdoptionSpeed','RescuerID'])
y_test = df_test['AdoptionSpeed']

In [28]:
# 1. Definir explícitamente qué variables son categóricas
categorical_cols = ['Type', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2', 'Color3', 
                    'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'State','Name','PetID','Description']


# Asegurarse de que el modelo entienda que son categorías (convertir a tipo 'category' en pandas)
for col in categorical_cols:
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')

# 2. Configurar K-Fold Cross Validation
N_SPLITS = 5
folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)

# Arreglos para guardar predicciones (Out-Of-Fold y Test)
oof_preds = np.zeros((len(X_train), 5)) # 5 es el número de clases
test_preds = np.zeros((len(X_test), 5))

# Nuevos parámetros base más controlados
lgb_params = {
    'objective': 'multiclass',
    'num_class': 5,
    'metric': 'multi_error',
    'learning_rate': 0.05,
    'num_leaves': 31,
    'max_depth': -1,
    'feature_fraction': 0.8,
    'seed': SEED,
    'verbose': -1
}

print("Iniciando entrenamiento con 5-Fold Cross Validation...")

for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
    print(f"\\n--- Fold {fold_ + 1} ---")
    
    # Separar datos del fold
    X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
    X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
    
    # Crear Datasets de LightGBM
    trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
    val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
    
    # Entrenar modelo usando callbacks modernos
    clf = lgb.train(
        lgb_params,
        trn_data,
        num_boost_round=1000,
        valid_sets=[trn_data, val_data],
        callbacks=[
            lgb.early_stopping(stopping_rounds=50, verbose=False),
            lgb.log_evaluation(period=100)
        ]
    )
    
    # Predecir sobre validación (Out-Of-Fold)
    oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)
    
    # Predecir sobre test (promediando los 5 folds)
    test_preds += clf.predict(X_test, num_iteration=clf.best_iteration) / N_SPLITS

# 3. Evaluar el modelo ensamblado
oof_predictions_classes = oof_preds.argmax(axis=1)
test_predictions_classes = test_preds.argmax(axis=1)

kappa_cv = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
kappa_test = cohen_kappa_score(y_test, test_predictions_classes, weights='quadratic')

print(f"\\nScore Kappa de Validación Cruzada (OOF): {kappa_cv:.4f}")
print(f"Score Kappa final en Test Set: {kappa_test:.4f}")

Iniciando entrenamiento con 5-Fold Cross Validation...
\n--- Fold 1 ---
[100]	training's multi_error: 0.410839	valid_1's multi_error: 0.580242
\n--- Fold 2 ---
[100]	training's multi_error: 0.40938	valid_1's multi_error: 0.588579
[200]	training's multi_error: 0.326212	valid_1's multi_error: 0.588995
\n--- Fold 3 ---
\n--- Fold 4 ---
[100]	training's multi_error: 0.404794	valid_1's multi_error: 0.601917
[200]	training's multi_error: 0.321939	valid_1's multi_error: 0.596499
\n--- Fold 5 ---
[100]	training's multi_error: 0.409337	valid_1's multi_error: 0.577148
\nScore Kappa de Validación Cruzada (OOF): 0.3629
Score Kappa final en Test Set: 0.3082

In [29]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
    'objective': 'multiclass',
    'num_class': 5,
    'metric': 'multi_error',
    'learning_rate': 0.05,
    'num_leaves': 31,
    'max_depth': -1,
    'feature_fraction': 0.8,
    'seed': SEED,
    'verbose': -1,
    'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.5, log=True),
    'num_leaves': trial.suggest_int('num_leaves', 10, 200),
    'max_depth': trial.suggest_int('max_depth', 7, 100),
    'feature_fraction': trial.suggest_float('feature_fraction', 0.4, 1.0),   
    }

    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=20)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-09 20:02:53,358] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

[I 2026-04-09 20:03:10,338] Trial 0 finished with value: 0.35737471250497965 and parameters: {'learning_rate': 0.05044902559051097, 'num_leaves': 97, 'max_depth': 77, 'feature_fraction': 0.6393665305211824}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:03:18,993] Trial 1 finished with value: 0.35669547707180205 and parameters: {'learning_rate': 0.2728503638624756, 'num_leaves': 32, 'max_depth': 48, 'feature_fraction': 0.5650039450823354}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:03:34,400] Trial 2 finished with value: 0.35006065333755765 and parameters: {'learning_rate': 0.23438192157488494, 'num_leaves': 113, 'max_depth': 66, 'feature_fraction': 0.9382943564458955}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:03:46,380] Trial 3 finished with value: 0.3480563830567952 and parameters: {'learning_rate': 0.1932535321420127, 'num_leaves': 72, 'max_depth': 80, 'feature_fraction': 0.7356734961864275}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:04:09,489] Trial 4 finished with value: 0.3368900523051733 and parameters: {'learning_rate': 0.25871896686803725, 'num_leaves': 148, 'max_depth': 89, 'feature_fraction': 0.49518585396276}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:04:25,863] Trial 5 finished with value: 0.3303379194027837 and parameters: {'learning_rate': 0.4975685745722375, 'num_leaves': 150, 'max_depth': 54, 'feature_fraction': 0.6588438603122091}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:04:30,471] Trial 6 finished with value: 0.35522640010496453 and parameters: {'learning_rate': 0.4045361218868964, 'num_leaves': 14, 'max_depth': 24, 'feature_fraction': 0.48003540170177866}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:04:54,462] Trial 7 finished with value: 0.33958046496197836 and parameters: {'learning_rate': 0.23804455298421534, 'num_leaves': 185, 'max_depth': 18, 'feature_fraction': 0.41241633872280703}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:05:14,619] Trial 8 finished with value: 0.35016480991245946 and parameters: {'learning_rate': 0.30071480950377183, 'num_leaves': 109, 'max_depth': 22, 'feature_fraction': 0.7724519974242678}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:05:35,584] Trial 9 finished with value: 0.3372719764404709 and parameters: {'learning_rate': 0.15557380751440422, 'num_leaves': 139, 'max_depth': 61, 'feature_fraction': 0.972530541826243}. Best is trial 0 with value: 0.35737471250497965.
[I 2026-04-09 20:05:51,412] Trial 10 finished with value: 0.36433800968368146 and parameters: {'learning_rate': 0.052829189684812664, 'num_leaves': 60, 'max_depth': 97, 'feature_fraction': 0.8273896572535855}. Best is trial 10 with value: 0.36433800968368146.
[I 2026-04-09 20:06:07,548] Trial 11 finished with value: 0.3572529219884829 and parameters: {'learning_rate': 0.050280682964187556, 'num_leaves': 65, 'max_depth': 92, 'feature_fraction': 0.8655953876373405}. Best is trial 10 with value: 0.36433800968368146.
[I 2026-04-09 20:06:22,641] Trial 12 finished with value: 0.35045997985967114 and parameters: {'learning_rate': 0.05153717320482684, 'num_leaves': 61, 'max_depth': 98, 'feature_fraction': 0.616972177279954}. Best is trial 10 with value: 0.36433800968368146.
[I 2026-04-09 20:06:40,547] Trial 13 finished with value: 0.3609300045450756 and parameters: {'learning_rate': 0.08211767982346473, 'num_leaves': 86, 'max_depth': 75, 'feature_fraction': 0.8244136551520996}. Best is trial 10 with value: 0.36433800968368146.
[I 2026-04-09 20:06:50,296] Trial 14 finished with value: 0.35935285331556344 and parameters: {'learning_rate': 0.08533813918822268, 'num_leaves': 42, 'max_depth': 76, 'feature_fraction': 0.831774763950139}. Best is trial 10 with value: 0.36433800968368146.
[W 2026-04-09 20:07:01,976] Trial 15 failed with parameters: {'learning_rate': 0.08409047453452335, 'num_leaves': 85, 'max_depth': 43, 'feature_fraction': 0.8693357722270834} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "c:\Users\fchiavassa\AppData\Local\Programs\Python\Python313\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\677189919.py", line 52, in objective
    oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)
                         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fchiavassa\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\basic.py", line 4767, in predict
    return predictor.predict(
           ~~~~~~~~~~~~~~~~~^
        data=data,
        ^^^^^^^^^^
    ...<6 lines>...
        validate_features=validate_features,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\fchiavassa\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\basic.py", line 1158, in predict
    data = _data_from_pandas(
           ~~~~~~~~~~~~~~~~~^
        data=data,
        ^^^^^^^^^^
    ...<2 lines>...
        pandas_categorical=self.pandas_categorical,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )[0]
    ^
  File "c:\Users\fchiavassa\AppData\Local\Programs\Python\Python313\Lib\site-packages\lightgbm\basic.py", line 853, in _data_from_pandas
    if list(data[col].cat.categories) != list(category):
            ~~~~^^^^^
  File "C:\Users\fchiavassa\AppData\Roaming\Python\Python313\site-packages\pandas\core\frame.py", line 4337, in __getitem__
    def __getitem__(self, key):

KeyboardInterrupt
[W 2026-04-09 20:07:01,981] Trial 15 failed with value None.

KeyboardInterrupt:

In [ ]:
import pandas as pd

# 1. Cargar el dataset original
# Asegúrate de que el archivo esté en la misma carpeta que tu notebook

def categorizar_tamano(row):
    breed = str(row['BreedName']).lower()
    pet_type = row['Type']
    
    # Gatos (Type = 2): Los clasificamos como 'Pequeño' por defecto en comparación a un perro
    if pet_type == 2:
        return 'Pequeño'
        
    # Perros (Type = 1)
    if 'mixed breed' in breed:
        return 'Mediano' # Promedio estadístico seguro para perros mestizos
        
    # A. Excepciones específicas (se evalúan antes que las reglas generales)
    excepciones_grandes = ['black russian terrier', 'airedale terrier', 'afghan hound', 'bloodhound', 'greyhound', 'irish wolfhound']
    excepciones_medianos = ['american staffordshire terrier', 'pit bull terrier', 'bull terrier', 'beagle', 'basset hound', 'whippet', 'standard schnauzer', 'cocker spaniel']
    excepciones_pequenos = ['dachshund', 'miniature schnauzer', 'toy', 'miniature']
    
    if any(exc in breed for exc in excepciones_grandes):
        return 'Grande'
    if any(exc in breed for exc in excepciones_medianos):
        return 'Mediano'
    if any(exc in breed for exc in excepciones_pequenos):
        return 'Pequeño'
        
    # B. Reglas generales por familias funcionales / palabras clave
    # La mayoría de los terriers y perros de compañía son pequeños
    keywords_pequenos = ['terrier', 'chihuahua', 'pomeranian', 'pug', 'shih tzu', 'maltese', 'pekingese', 'corgi', 'bichon', 'french bulldog', 'papillon', 'havanese', 'pinscher']
    
    # La mayoría de los pastores, cobradores, mastines y sabuesos son grandes
    keywords_grandes = ['retriever', 'shepherd', 'mastiff', 'great', 'husky', 'malamute', 'akita', 'hound', 'pointer', 'setter', 'collie', 'rottweiler', 'doberman', 'boxer', 'american bulldog', 'sheepdog', 'dane', 'bernard', 'pyrenees', 'newfoundland', 'weimaraner', 'ridgeback', 'corso', 'komondor', 'kuvasz', 'borzoi', 'dalmatian']
    
    if any(kw in breed for kw in keywords_pequenos):
        return 'Pequeño'
    if any(kw in breed for kw in keywords_grandes):
        return 'Grande'
        
    # C. Todo lo que no caiga en las reglas anteriores se asume Mediano (ej. Spaniels, Bulldogs ingleses, Spitz)
    return 'Mediano'

# 2. Aplicar la función para crear la nueva columna
breed_df['SizeCategory'] = breed_df.apply(categorizar_tamano, axis=1)

# Unimos indicando que Breed1 equivale a BreedID
df_train = df_train.merge(
    breed_df[['BreedID', 'SizeCategory']], 
    left_on='Breed1', 
    right_on='BreedID', 
    how='left'
)

df_test = df_test.merge(
    breed_df[['BreedID', 'SizeCategory']], 
    left_on='Breed1', 
    right_on='BreedID', 
    how='left'
)

# Opcional: eliminar la columna BreedID duplicada que queda tras el merge
df_train = df_train.drop(columns=['BreedID'])
df_test = df_test.drop(columns=['BreedID'])
# 3. Exportar el resultado a un nuevo archivo CSV
nuevo_archivo = 'PetFinder-BreedLabels-Sized.csv'
breed_df.to_csv(nuevo_archivo, index=False)

print(f"Archivo generado exitosamente: '{nuevo_archivo}'")
print("\nMuestra de cómo quedaron las categorías:")
display(breed_df.sample(10, random_state=42))

In [91]:
# Creamos un diccionario para acumular las nuevas columnas rápidamente
nuevas_features = {}

# 1. Interacciones de Edad y Atributos Físicos
# Una mascota vieja y grande suele tardar más en adoptarse que una vieja y pequeña
nuevas_features['Age_x_MaturitySize'] = df_train['Age'] * df_train['MaturitySize']
nuevas_features['Age_x_MaturitySize'] = df_test['Age'] * df_test['MaturitySize']


# 2. Interacciones de Costo y Raza
# El impacto del Fee (costo) puede variar según si la raza es pura (Breed2 == 0) o no
nuevas_features['Fee_x_Breed1'] = df_train['Fee'] * df_train['Breed1']
nuevas_features['Fee_x_Breed1'] = df_test['Fee'] * df_test['Breed1']


# 3. Interacciones de Esfuerzo del Rescatista (Las más importantes según tu lista)
# ¿El rescatista que tiene muchas fotos (PhotoAmt) tiene mejor suerte con ciertas edades?
nuevas_features['Age_x_PhotoAmt'] = df_train['Age'] * df_train['PhotoAmt']
nuevas_features['Age_x_PhotoAmt'] = df_test['Age'] * df_test['PhotoAmt']

# 4. Interacciones de Salud y Cuidados
# Estar vacunado, desparasitado y esterilizado combinado
nuevas_features['Salud_Completa'] = df_train['Vaccinated'] * df_train['Dewormed'] * df_train['Sterilized']
nuevas_features['Salud_Completa'] = df_test['Vaccinated'] * df_test['Dewormed'] * df_test['Sterilized']

# 5. Ratio de Fotos por Cantidad de Mascotas
# Si hay muchos animales en la publicación (Quantity), ¿hay suficientes fotos para todos?
nuevas_features['Photos_per_Pet'] = df_train['PhotoAmt'] / (df_train['Quantity'] + 1)
nuevas_features['Photos_per_Pet'] = df_test['PhotoAmt'] / (df_test['Quantity'] + 1)

# 6. Cruces de Color y Raza (Estética)
nuevas_features['Breed_x_Color1'] = df_train['Breed1'] * df_train['Color1']
nuevas_features['Breed_x_Color1'] = df_test['Breed1'] * df_test['Color1']

# --- CONCATENACIÓN FINAL ---
print("Agregando interacciones seleccionadas al dataset...")
df_interacciones = pd.DataFrame(nuevas_features)
df_train = pd.concat([df_train, df_interacciones], axis=1)
df_test = pd.concat([df_test, df_interacciones], axis=1)

print(f"Se han agregado {len(nuevas_features)} columnas estratégicas.")
print(f"Nuevo tamaño del dataset: {df_train.shape}")

Agregando interacciones seleccionadas al dataset...
Se han agregado 6 columnas estratégicas.
Nuevo tamaño del dataset: (11994, 31)

In [92]:
def crear_variables_agregadas(df_train):
    # --- 1. Estadísticas por RescuerID (El perfil del rescatista) ---
    # Cantidad de mascotas subidas por cada rescatista
    df_train['rescu_total_pets'] = df_train.groupby('RescuerID')['RescuerID'].transform('count')
    
    # Promedio de fotos que sube este rescatista (indica calidad de perfil)
    df_train['rescu_avg_photos'] = df_train.groupby('RescuerID')['PhotoAmt'].transform('mean')
    
    # Promedio de precio que cobra este rescatista
    df_train['rescu_avg_fee'] = df_train.groupby('RescuerID')['Fee'].transform('mean')

    # --- 2. Estadísticas por Breed1 (El perfil de la raza) ---
    # ¿Qué tan común es esta raza en el dataset?
    df_train['breed_popularity'] = df_train.groupby('Breed1')['Breed1'].transform('count')
    
    # Promedio de edad para esta raza (algunas razas se abandonan más adultas)
    df_train['breed_avg_age'] = df_train.groupby('Breed1')['Age'].transform('mean')
    
    # Promedio de Fee para esta raza (hay razas que siempre son caras)
    df_train['breed_avg_fee'] = df_train.groupby('Breed1')['Fee'].transform('mean')

    # --- 3. Interacción: Rescatista x Raza ---
    # ¿Cuántas veces este rescatista trabajó con esta raza específica?
    df_train['rescu_breed_experience'] = df_train.groupby(['RescuerID', 'Breed1'])['PetID'].transform('count')

    return df_train

# Aplicamos a tu dataset
df_train = crear_variables_agregadas(df_train)
# Repetir lo mismo para el test_df si lo tenés aparte

def crear_variables_agregadas(df_test):
    # --- 1. Estadísticas por RescuerID (El perfil del rescatista) ---
    # Cantidad de mascotas subidas por cada rescatista
    df_test['rescu_total_pets'] = df_test.groupby('RescuerID')['RescuerID'].transform('count')
    
    # Promedio de fotos que sube este rescatista (indica calidad de perfil)
    df_test['rescu_avg_photos'] = df_test.groupby('RescuerID')['PhotoAmt'].transform('mean')
    
    # Promedio de precio que cobra este rescatista
    df_test['rescu_avg_fee'] = df_test.groupby('RescuerID')['Fee'].transform('mean')

    # --- 2. Estadísticas por Breed1 (El perfil de la raza) ---
    # ¿Qué tan común es esta raza en el dataset?
    df_test['breed_popularity'] = df_test.groupby('Breed1')['Breed1'].transform('count')
    
    # Promedio de edad para esta raza (algunas razas se abandonan más adultas)
    df_test['breed_avg_age'] = df_test.groupby('Breed1')['Age'].transform('mean')
    
    # Promedio de Fee para esta raza (hay razas que siempre son caras)
    df_test['breed_avg_fee'] = df_test.groupby('Breed1')['Fee'].transform('mean')

    # --- 3. Interacción: Rescatista x Raza ---
    # ¿Cuántas veces este rescatista trabajó con esta raza específica?
    df_test['rescu_breed_experience'] = df_test.groupby(['RescuerID', 'Breed1'])['PetID'].transform('count')

    return df_test

# Aplicamos a tu dataset
df_test = crear_variables_agregadas(df_test)

In [93]:
#Genero dataframes de train y test con sus respectivos targets
X_train = df_train.drop(columns=['AdoptionSpeed'])
y_train = df_train['AdoptionSpeed']

X_test = df_test.drop(columns=['AdoptionSpeed'])
y_test = df_test['AdoptionSpeed']

In [96]:
# 1. Definir explícitamente qué variables son categóricas
categorical_cols = ['Type', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2', 'Color3', 
                    'Vaccinated', 'Dewormed', 'Sterilized', 'Health', 'State','SizeCategory','Name','PetID','Description','RescuerID']


# Asegurarse de que el modelo entienda que son categorías (convertir a tipo 'category' en pandas)
for col in categorical_cols:
    X_train[col] = X_train[col].astype('category')
    X_test[col] = X_test[col].astype('category')

In [97]:
X_train

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Salud_Completa,Photos_per_Pet,Breed_x_Color1,rescu_total_pets,rescu_avg_photos,rescu_avg_fee,breed_popularity,breed_avg_age,breed_avg_fee,rescu_breed_experience
0,1,The Adorable Trio,2,307,307,1,1,0,0,2,...,8.0,3.000000,307.0,1,8.000000,0.000000,4754,7.558687,9.696466,1
1,1,Perky,12,307,0,2,2,0,0,1,...,2.0,1.000000,103.0,33,2.181818,0.000000,4754,7.558687,9.696466,12
2,1,Bernard Boy,2,307,307,1,1,2,7,2,...,2.0,0.833333,614.0,31,5.193548,52.870968,4754,7.558687,9.696466,28
3,1,Oreo 1,2,307,307,1,3,0,0,2,...,2.0,3.000000,530.0,180,3.127778,11.111111,4754,7.558687,9.696466,165
4,2,Anak Kucing,4,265,0,3,1,2,0,2,...,8.0,2.666667,532.0,1,2.000000,0.000000,983,6.342828,10.769074,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11989,2,Maxine,8,265,299,2,1,2,0,2,...,NaN,NaN,NaN,1,2.000000,0.000000,983,6.342828,10.769074,1
11990,1,Browny,2,307,0,2,6,7,0,1,...,NaN,NaN,NaN,1,1.000000,0.000000,4754,7.558687,9.696466,1
11991,1,Midnight,2,307,307,1,1,0,0,2,...,NaN,NaN,NaN,4,2.000000,0.000000,4754,7.558687,9.696466,4
11992,1,Boxer,2,307,307,1,1,2,7,2,...,NaN,NaN,NaN,111,2.234234,0.000000,4754,7.558687,9.696466,99
11993,2,JINGGA,30,299,266,1,3,4,5,2,...,NaN,NaN,NaN,1,2.000000,0.000000,280,7.371429,11.628571,1

In [30]:
import lightgbm as lgb
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ============================================================================
# 1. Preparación de Datasets (Uso de validación real)
# ============================================================================
# Es fundamental que valid_sets reciba datos que el modelo NO vio en el training
dtrain = lgb.Dataset(X_train, label=y_train, free_raw_data=False)
dvalid = lgb.Dataset(X_test, label=y_test, reference=dtrain)

# ============================================================================
# 2. Parámetros y Entrenamiento
# ============================================================================
params = {
    'objective': 'multiclass',
    'num_class': 5,
    'metric': 'multi_error',
    'verbosity': -1,
    'learning_rate': 0.05,
    'num_leaves': 31,
    'max_depth': 7,
    'min_data_in_leaf': 20,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'random_state': 42
}

print("Entrenando modelo con Early Stopping...")
model = lgb.train(
    params,
    dtrain,
    num_boost_round=1000,
    valid_sets=[dtrain, dvalid],
    valid_names=['train', 'valid'],
    callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=True)]
)

# ============================================================================
# 3. Importancia de Variables (Gain)
# ============================================================================
importance_type = 'gain' 

feature_importances = model.feature_importance(importance_type=importance_type)
feature_names = X_train.columns

# Crear DataFrame de importancia
df_importance = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances,
    'importance_pct': (feature_importances / feature_importances.sum() * 100).round(2) if feature_importances.sum() > 0 else 0
}).sort_values('importance', ascending=False).reset_index(drop=True)

# Mostrar resultados
print("\n=== Top 60 Importancia de Features (Gain) ===")
print(df_importance.head(60))

Entrenando modelo con Early Stopping...
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[31]	train's multi_error: 0.52618	valid's multi_error: 0.614538

=== Top 60 Importancia de Features (Gain) ===
         feature   importance  importance_pct
0            Age  9069.527051           21.71
1         Breed1  7748.633011           18.55
2       PhotoAmt  5801.997793           13.89
3     Sterilized  3597.491404            8.61
4       Quantity  2063.976989            4.94
5            Fee  1412.836911            3.38
6   MaturitySize  1320.117599            3.16
7          State  1305.514130            3.12
8         Breed2  1279.608050            3.06
9         Gender  1247.400281            2.99
10      Dewormed  1229.186012            2.94
11    Vaccinated  1183.843136            2.83
12     FurLength   912.608391            2.18
13          Type   863.749701            2.07
14          Name   819.123665            1.96
15        Color1   793.234570            1.90
16        Color2   509.804728            1.22
17      VideoAmt   196.131669            0.47
18        Health   171.970850            0.41
19        Color3   156.794459            0.38
20   Description    96.517719            0.23
21         PetID     0.000000            0.00

In [99]:
import pandas as pd
import numpy as np
from sklearn.metrics import average_precision_score

# ==========================================================
# 1. CÁLCULO DE GAIN (TABLA 1)
# ==========================================================
print("Calculando importancia por Gain...")
df_gain = pd.DataFrame({
    'feature': X_train.columns,
    'gain': model.feature_importance(importance_type='gain')
})

# ==========================================================
# 2. CÁLCULO DE PERMUTATION IMPACT (TABLA 2)
# ==========================================================
print("\nIniciando auditoría de impacto en Test (Permutation)...")

def get_full_audit(model, X_test_audit, y):
    # Aseguramos que el orden de columnas sea idéntico al de entrenamiento
    features = X_train.columns.tolist()
    X_test_audit = X_test_audit[features]
    
    # Predicción base
    y_pred_base = model.predict(X_test_audit).reshape(-1, 1)
    baseline_score = average_precision_score(y, y_pred_base)
    
    print(f"Baseline PR-AUC en Test: {baseline_score:.4f}")
    
    results = []
    
    for i, col in enumerate(features):
        # Copiamos la columna original para no romper el DataFrame
        original_col = X_test_audit[col].copy()
        
        # PERMUTACIÓN:
        # Si es categórica, debemos mantener el tipo 'category' al permutar
        if X_test_audit[col].dtype.name == 'category':
            permuted_values = np.random.permutation(X_test_audit[col].values)
            X_test_audit[col] = pd.Series(permuted_values).astype('category').values
            # Reasignamos las categorías originales para que LightGBM no se queje
            X_test_audit[col] = X_test_audit[col].cat.set_categories(original_col.cat.categories)
        else:
            X_test_audit[col] = np.random.permutation(X_test_audit[col].values)
        
        # Medimos impacto con el modelo
        try:
            y_pred_shuffled = model.predict(X_test_audit).reshape(-1, 1)
            shuffled_score = average_precision_score(y, y_pred_shuffled)
            drop = baseline_score - shuffled_score
        except ValueError:
            # Si falla por categorías, forzamos el re-tipado rápido
            for c in X_test_audit.select_dtypes(['category']).columns:
                X_test_audit[c] = X_test_audit[c].astype('category')
            y_pred_shuffled = model.predict(X_test_audit).reshape(-1, 1)
            shuffled_score = average_precision_score(y, y_pred_shuffled)
            drop = baseline_score - shuffled_score

        results.append(drop)
        
        # RESTAURACIÓN: fundamental devolver la columna a su estado previo
        X_test_audit[col] = original_col
        
        if (i+1) % 5 == 0 or i == 0:
            print(f"[{i+1}/{len(features)}] Auditada: {col} | Drop: {drop:.6f}")
            
    return pd.DataFrame({'feature': features, 'test_impact': results})

# Ejecutamos la auditoría sobre una copia limpia
df_audit = get_full_audit(model, X_test.copy(), y_test)

# ==========================================================
# 3. UNIFICACIÓN Y TABLA FINAL
# ==========================================================
df_final = pd.merge(df_gain, df_audit, on='feature')

# Ordenamos por impacto real en Test (Permutation)
df_final = df_final.sort_values('test_impact', ascending=False).reset_index(drop=True)

# Agregamos % de Gain para comparar
df_final['gain_pct'] = (df_final['gain'] / df_final['gain'].sum() * 100).round(2)

print("\n" + "="*60)
print("=== MATRIZ DE DECISIÓN FINAL (GAIN vs IMPACT) ===")
print("="*60)
print(df_final[['feature', 'gain', 'test_impact', 'gain_pct']].to_string(index=False))

# Guardar
df_final.to_csv('matriz_final_maestria.csv', index=False)

Calculando importancia por Gain...

Iniciando auditoría de impacto en Test (Permutation)...
Baseline PR-AUC en Test: 0.0186
[1/37] Auditada: Type | Drop: -0.000000
[5/37] Auditada: Breed2 | Drop: -0.000341
[10/37] Auditada: MaturitySize | Drop: 0.000064
[15/37] Auditada: Health | Drop: 0.000019
[20/37] Auditada: VideoAmt | Drop: 0.000006
[25/37] Auditada: Age_x_MaturitySize | Drop: -0.000100
[30/37] Auditada: Breed_x_Color1 | Drop: 0.000160
[35/37] Auditada: breed_avg_age | Drop: -0.000057

============================================================
=== MATRIZ DE DECISIÓN FINAL (GAIN vs IMPACT) ===
============================================================
               feature         gain   test_impact  gain_pct
                Breed1  9231.193295  3.342429e-04      3.94
                   Age 10851.749149  1.830042e-04      4.63
        Breed_x_Color1  2395.813111  1.600452e-04      1.02
              Dewormed  4276.702014  1.218434e-04      1.82
        Salud_Completa  2423.510235  1.152169e-04      1.03
                Color1  2375.482496  1.063340e-04      1.01
          MaturitySize  2730.741505  6.381368e-05      1.16
                Health   552.455420  1.886282e-05      0.24
          Fee_x_Breed1   710.720867  8.465187e-06      0.30
              VideoAmt   476.744219  6.308234e-06      0.20
                Gender  3095.702355  4.840095e-06      1.32
                Color3   360.485104  2.853900e-06      0.15
          SizeCategory   920.684695  2.692842e-06      0.39
           Description   129.772301  1.934013e-06      0.06
                 PetID     0.000000  0.000000e+00      0.00
                  Type   242.253643 -1.763078e-07      0.10
                Color2  1989.378585 -2.355382e-06      0.85
            Vaccinated  2802.404023 -9.900933e-06      1.20
         rescu_avg_fee  8115.378522 -1.764029e-05      3.46
      rescu_avg_photos  8462.123156 -3.594490e-05      3.61
         breed_avg_age  4566.254807 -5.650235e-05      1.95
              Quantity  3796.272130 -7.551721e-05      1.62
             FurLength  2619.332606 -9.166692e-05      1.12
rescu_breed_experience  4742.178027 -9.927097e-05      2.02
    Age_x_MaturitySize  2291.889535 -1.003752e-04      0.98
                 State  2143.658803 -1.035144e-04      0.91
            Sterilized  2801.459939 -1.307432e-04      1.20
              PhotoAmt  8770.620327 -1.325169e-04      3.74
                   Fee  2372.321961 -1.991155e-04      1.01
         breed_avg_fee 16270.646234 -2.383366e-04      6.94
        Age_x_PhotoAmt  4866.352171 -2.591341e-04      2.08
      breed_popularity  6407.916506 -3.292647e-04      2.73
                Breed2  4399.498284 -3.405299e-04      1.88
        Photos_per_Pet  3935.215120 -3.531292e-04      1.68
                  Name 11402.418486 -4.833759e-04      4.86
      rescu_total_pets 26047.339251 -1.991772e-03     11.11
             RescuerID 64843.753700 -4.428272e-03     27.66

In [12]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.5, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 50, 200),
        'max_depth': trial.suggest_int('max_depth', 7, 50),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.6, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.6, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 10, 50),
        'min_child_samples': trial.suggest_int('min_child_samples', 100, 3000),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.5, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.01,5.0, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.01, 0.2, log=True), # Peaje más caro para abrir ramas 
    }


    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=500)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

c:\Users\fchiavassa\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2026-04-09 19:46:11,919] A new study created in memory with name: Petfinder_LGBM_Optuna
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),

Iniciando búsqueda de hiperparámetros con Optuna...

[I 2026-04-09 19:46:18,437] Trial 0 finished with value: 0.3824249379001148 and parameters: {'learning_rate': 0.35201421741381955, 'num_leaves': 94, 'max_depth': 17, 'feature_fraction': 0.9128877181712357, 'bagging_fraction': 0.9834534507546357, 'bagging_freq': 48, 'min_child_samples': 509, 'min_data_in_leaf': 83, 'lambda_l1': 0.0015504433049905945, 'lambda_l2': 0.3547821134921013, 'min_gain_to_split': 0.02126456081939171}. Best is trial 0 with value: 0.3824249379001148.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:46:25,056] Trial 1 finished with value: 0.3806273229464473 and parameters: {'learning_rate': 0.36595081458674894, 'num_leaves': 146, 'max_depth': 20, 'feature_fraction': 0.7779593716830477, 'bagging_fraction': 0.9768960400370642, 'bagging_freq': 30, 'min_child_samples': 778, 'min_data_in_leaf': 98, 'lambda_l1': 0.02323321625125221, 'lambda_l2': 0.022843842773599528, 'min_gain_to_split': 0.06862181733625747}. Best is trial 0 with value: 0.3824249379001148.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:46:34,381] Trial 2 finished with value: 0.37153679722226507 and parameters: {'learning_rate': 0.2441352357556001, 'num_leaves': 197, 'max_depth': 45, 'feature_fraction': 0.8189063001677299, 'bagging_fraction': 0.7680748455951302, 'bagging_freq': 44, 'min_child_samples': 1857, 'min_data_in_leaf': 108, 'lambda_l1': 0.09033961457190283, 'lambda_l2': 2.480161771596313, 'min_gain_to_split': 0.06495904008243582}. Best is trial 0 with value: 0.3824249379001148.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:46:45,253] Trial 3 finished with value: 0.38243447387577023 and parameters: {'learning_rate': 0.11458551856016579, 'num_leaves': 118, 'max_depth': 15, 'feature_fraction': 0.6588954143527751, 'bagging_fraction': 0.7384452407412039, 'bagging_freq': 14, 'min_child_samples': 2898, 'min_data_in_leaf': 67, 'lambda_l1': 0.008541939926334759, 'lambda_l2': 0.053849330185176306, 'min_gain_to_split': 0.05125096269158826}. Best is trial 3 with value: 0.38243447387577023.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:46:53,660] Trial 4 finished with value: 0.3668793627566137 and parameters: {'learning_rate': 0.1139550026786677, 'num_leaves': 105, 'max_depth': 44, 'feature_fraction': 0.6878964071631559, 'bagging_fraction': 0.866987973554044, 'bagging_freq': 23, 'min_child_samples': 857, 'min_data_in_leaf': 90, 'lambda_l1': 0.05514936843322116, 'lambda_l2': 1.017313343897094, 'min_gain_to_split': 0.19678891294289574}. Best is trial 3 with value: 0.38243447387577023.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:47:12,189] Trial 5 finished with value: 0.3705578893561179 and parameters: {'learning_rate': 0.07698549984629123, 'num_leaves': 101, 'max_depth': 34, 'feature_fraction': 0.9848876899944466, 'bagging_fraction': 0.6031636259009658, 'bagging_freq': 29, 'min_child_samples': 2150, 'min_data_in_leaf': 46, 'lambda_l1': 0.01726438748217591, 'lambda_l2': 0.17003298855483528, 'min_gain_to_split': 0.028208687669793564}. Best is trial 3 with value: 0.38243447387577023.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:47:25,229] Trial 6 finished with value: 0.36075073895328247 and parameters: {'learning_rate': 0.19834866523031394, 'num_leaves': 74, 'max_depth': 36, 'feature_fraction': 0.7278258631962701, 'bagging_fraction': 0.6335210571491899, 'bagging_freq': 20, 'min_child_samples': 1696, 'min_data_in_leaf': 49, 'lambda_l1': 0.03421617743657863, 'lambda_l2': 0.011771414625442504, 'min_gain_to_split': 0.11978959875964132}. Best is trial 3 with value: 0.38243447387577023.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:47:33,426] Trial 7 finished with value: 0.3862842925986396 and parameters: {'learning_rate': 0.24054209049450234, 'num_leaves': 133, 'max_depth': 13, 'feature_fraction': 0.8814845808290213, 'bagging_fraction': 0.8740924703871225, 'bagging_freq': 50, 'min_child_samples': 755, 'min_data_in_leaf': 87, 'lambda_l1': 0.08163163657863377, 'lambda_l2': 0.015253244501847353, 'min_gain_to_split': 0.1467275979642685}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:47:49,011] Trial 8 finished with value: 0.380683829174454 and parameters: {'learning_rate': 0.07911064499485972, 'num_leaves': 152, 'max_depth': 26, 'feature_fraction': 0.9690943067140592, 'bagging_fraction': 0.7596562251568313, 'bagging_freq': 27, 'min_child_samples': 818, 'min_data_in_leaf': 117, 'lambda_l1': 0.13282390120478357, 'lambda_l2': 0.051685080814013115, 'min_gain_to_split': 0.13460622741896344}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:47:56,556] Trial 9 finished with value: 0.36485934042218005 and parameters: {'learning_rate': 0.39979320938151136, 'num_leaves': 80, 'max_depth': 44, 'feature_fraction': 0.874179980103645, 'bagging_fraction': 0.6287295724610781, 'bagging_freq': 42, 'min_child_samples': 1446, 'min_data_in_leaf': 100, 'lambda_l1': 0.014210063013263878, 'lambda_l2': 0.027075749856910195, 'min_gain_to_split': 0.010043302167580733}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:48:08,088] Trial 10 finished with value: 0.3840412499023459 and parameters: {'learning_rate': 0.24206745110204442, 'num_leaves': 178, 'max_depth': 8, 'feature_fraction': 0.6034102798065856, 'bagging_fraction': 0.8776437356397729, 'bagging_freq': 38, 'min_child_samples': 225, 'min_data_in_leaf': 67, 'lambda_l1': 0.2839553360680935, 'lambda_l2': 0.17670197576993862, 'min_gain_to_split': 0.09389644705634277}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:48:16,640] Trial 11 finished with value: 0.38267333340342113 and parameters: {'learning_rate': 0.23488445058297, 'num_leaves': 192, 'max_depth': 7, 'feature_fraction': 0.6134445323089122, 'bagging_fraction': 0.8773647707059891, 'bagging_freq': 37, 'min_child_samples': 166, 'min_data_in_leaf': 68, 'lambda_l1': 0.4854605568640465, 'lambda_l2': 0.17604764981864338, 'min_gain_to_split': 0.10496122486686252}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:48:25,580] Trial 12 finished with value: 0.38359912768198323 and parameters: {'learning_rate': 0.15431088187101866, 'num_leaves': 159, 'max_depth': 10, 'feature_fraction': 0.8433128277244327, 'bagging_fraction': 0.8614924774715985, 'bagging_freq': 37, 'min_child_samples': 156, 'min_data_in_leaf': 68, 'lambda_l1': 0.32004168843240355, 'lambda_l2': 0.5103455848666542, 'min_gain_to_split': 0.19550915108246575}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:48:33,019] Trial 13 finished with value: 0.384446532594775 and parameters: {'learning_rate': 0.4930547710565574, 'num_leaves': 172, 'max_depth': 13, 'feature_fraction': 0.7746953958200444, 'bagging_fraction': 0.9173589801070764, 'bagging_freq': 50, 'min_child_samples': 1224, 'min_data_in_leaf': 58, 'lambda_l1': 0.18965772690751917, 'lambda_l2': 4.685607211026434, 'min_gain_to_split': 0.08645885626619233}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:48:43,333] Trial 14 finished with value: 0.368711528943213 and parameters: {'learning_rate': 0.4744909986650366, 'num_leaves': 133, 'max_depth': 24, 'feature_fraction': 0.7476618698644071, 'bagging_fraction': 0.9308685505967172, 'bagging_freq': 50, 'min_child_samples': 1188, 'min_data_in_leaf': 56, 'lambda_l1': 0.16170524168927355, 'lambda_l2': 3.9009082240781585, 'min_gain_to_split': 0.03566297642106356}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:49:02,925] Trial 15 finished with value: 0.3715221942684527 and parameters: {'learning_rate': 0.052502555930016556, 'num_leaves': 170, 'max_depth': 14, 'feature_fraction': 0.907947325000946, 'bagging_fraction': 0.8263462775846061, 'bagging_freq': 44, 'min_child_samples': 1152, 'min_data_in_leaf': 79, 'lambda_l1': 0.06454196859333038, 'lambda_l2': 1.3242922782269526, 'min_gain_to_split': 0.07851650491863742}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:49:13,925] Trial 16 finished with value: 0.38005933072814146 and parameters: {'learning_rate': 0.3118221983846743, 'num_leaves': 50, 'max_depth': 21, 'feature_fraction': 0.7807946085741457, 'bagging_fraction': 0.909744498644185, 'bagging_freq': 50, 'min_child_samples': 2452, 'min_data_in_leaf': 58, 'lambda_l1': 0.006383028430693831, 'lambda_l2': 0.08171404676907039, 'min_gain_to_split': 0.1345637391049214}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:49:25,444] Trial 17 finished with value: 0.374375012937303 and parameters: {'learning_rate': 0.49350413062057646, 'num_leaves': 130, 'max_depth': 32, 'feature_fraction': 0.8513092747021836, 'bagging_fraction': 0.9383978848642243, 'bagging_freq': 41, 'min_child_samples': 1292, 'min_data_in_leaf': 40, 'lambda_l1': 0.16245664147120278, 'lambda_l2': 4.650348530348552, 'min_gain_to_split': 0.04703770761514155}. Best is trial 7 with value: 0.3862842925986396.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 120, 1),
[I 2026-04-09 19:49:38,911] Trial 18 finished with value: 0.387906397838666 and parameters: {'learning_rate': 0.15561916376326448, 'num_leaves': 177, 'max_depth': 13, 'feature_fraction': 0.9132731160522803, 'bagging_fraction': 0.8161645634363883, 'bagging_freq': 34, 'min_child_samples': 533, 'min_data_in_leaf': 79, 'lambda_l1': 0.03835810645474552, 'lambda_l2': 0.7864340513988178, 'min_gain_to_split': 0.16224149420639147}. Best is trial 18 with value: 0.387906397838666.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_23656\1294875881.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.

KeyboardInterrupt:

In [102]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.03, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 100, 250),
        'max_depth': trial.suggest_int('max_depth', 22, 60),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.7, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.7, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 15, 30),
        'min_child_samples': trial.suggest_int('min_child_samples', 1000, 3000),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.1, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.01,1.0, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.01, 0.1, log=True), # Peaje más caro para abrir ramas 
    }

    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=500)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-08 12:50:07,264] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:50:19,322] Trial 0 finished with value: 0.40662448046712507 and parameters: {'learning_rate': 0.04448103549624654, 'num_leaves': 212, 'max_depth': 45, 'feature_fraction': 0.9321236252962755, 'bagging_fraction': 0.952525001997167, 'bagging_freq': 15, 'min_child_samples': 2268, 'min_data_in_leaf': 67, 'lambda_l1': 0.05554702068756175, 'lambda_l2': 0.03393596022318814, 'min_gain_to_split': 0.024669446726698865}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:50:28,357] Trial 1 finished with value: 0.3875031628749902 and parameters: {'learning_rate': 0.05602382017267713, 'num_leaves': 182, 'max_depth': 28, 'feature_fraction': 0.8410614151419955, 'bagging_fraction': 0.7632518668812337, 'bagging_freq': 25, 'min_child_samples': 1770, 'min_data_in_leaf': 89, 'lambda_l1': 0.015299764779112672, 'lambda_l2': 0.02644920095246439, 'min_gain_to_split': 0.01803099954931844}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:50:43,468] Trial 2 finished with value: 0.3949291964091729 and parameters: {'learning_rate': 0.035275385284669114, 'num_leaves': 213, 'max_depth': 32, 'feature_fraction': 0.8801891274175141, 'bagging_fraction': 0.7737460393279407, 'bagging_freq': 15, 'min_child_samples': 1129, 'min_data_in_leaf': 50, 'lambda_l1': 0.010315100398931801, 'lambda_l2': 0.9285145507460816, 'min_gain_to_split': 0.08550781554975098}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:50:53,900] Trial 3 finished with value: 0.3905809335291538 and parameters: {'learning_rate': 0.044543023997709444, 'num_leaves': 104, 'max_depth': 28, 'feature_fraction': 0.8147076031679104, 'bagging_fraction': 0.790470835706733, 'bagging_freq': 16, 'min_child_samples': 2547, 'min_data_in_leaf': 75, 'lambda_l1': 0.01179985609368106, 'lambda_l2': 0.02402169127602281, 'min_gain_to_split': 0.014834857207376288}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:51:05,648] Trial 4 finished with value: 0.39646203364672994 and parameters: {'learning_rate': 0.07418426346722355, 'num_leaves': 169, 'max_depth': 38, 'feature_fraction': 0.818588408472644, 'bagging_fraction': 0.8671967472905789, 'bagging_freq': 29, 'min_child_samples': 2245, 'min_data_in_leaf': 63, 'lambda_l1': 0.00660605368334117, 'lambda_l2': 0.2726261532863872, 'min_gain_to_split': 0.019382719654448443}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:51:16,342] Trial 5 finished with value: 0.40072798726076864 and parameters: {'learning_rate': 0.07955099255276486, 'num_leaves': 162, 'max_depth': 26, 'feature_fraction': 0.9268519273213081, 'bagging_fraction': 0.8120313112071035, 'bagging_freq': 16, 'min_child_samples': 1153, 'min_data_in_leaf': 100, 'lambda_l1': 0.04355945086665802, 'lambda_l2': 0.7831427700946115, 'min_gain_to_split': 0.0390595504871913}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:51:33,481] Trial 6 finished with value: 0.4016649336571818 and parameters: {'learning_rate': 0.06293132002683648, 'num_leaves': 189, 'max_depth': 35, 'feature_fraction': 0.9631474959836774, 'bagging_fraction': 0.7214447668515951, 'bagging_freq': 16, 'min_child_samples': 1961, 'min_data_in_leaf': 48, 'lambda_l1': 0.018247081944429578, 'lambda_l2': 0.34247829103688215, 'min_gain_to_split': 0.04188644896836063}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:51:44,878] Trial 7 finished with value: 0.3750212487419311 and parameters: {'learning_rate': 0.044892317421323956, 'num_leaves': 245, 'max_depth': 58, 'feature_fraction': 0.7251408929452999, 'bagging_fraction': 0.7506159080847234, 'bagging_freq': 18, 'min_child_samples': 1923, 'min_data_in_leaf': 98, 'lambda_l1': 0.065243515849739, 'lambda_l2': 0.07297006592893523, 'min_gain_to_split': 0.01960038041303813}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:52:03,591] Trial 8 finished with value: 0.40378544678778283 and parameters: {'learning_rate': 0.04820288952507364, 'num_leaves': 238, 'max_depth': 58, 'feature_fraction': 0.9385338707909598, 'bagging_fraction': 0.9538419780496661, 'bagging_freq': 25, 'min_child_samples': 2532, 'min_data_in_leaf': 76, 'lambda_l1': 0.002457343307450891, 'lambda_l2': 0.1363555833777129, 'min_gain_to_split': 0.09784803908958138}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:52:17,382] Trial 9 finished with value: 0.3939519074193544 and parameters: {'learning_rate': 0.05621706766116721, 'num_leaves': 154, 'max_depth': 55, 'feature_fraction': 0.7343786097064664, 'bagging_fraction': 0.854300161532051, 'bagging_freq': 23, 'min_child_samples': 2151, 'min_data_in_leaf': 91, 'lambda_l1': 0.0017292227867639893, 'lambda_l2': 0.725394209471529, 'min_gain_to_split': 0.02667630932201695}. Best is trial 0 with value: 0.40662448046712507.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:52:39,145] Trial 10 finished with value: 0.4076755677426138 and parameters: {'learning_rate': 0.03181695673025516, 'num_leaves': 121, 'max_depth': 50, 'feature_fraction': 0.9886194485695045, 'bagging_fraction': 0.9815280226399686, 'bagging_freq': 20, 'min_child_samples': 2892, 'min_data_in_leaf': 62, 'lambda_l1': 0.03543216324123859, 'lambda_l2': 0.011217260251742038, 'min_gain_to_split': 0.010051286848867894}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:53:01,638] Trial 11 finished with value: 0.40666711916361864 and parameters: {'learning_rate': 0.030943135170115158, 'num_leaves': 118, 'max_depth': 46, 'feature_fraction': 0.9885066375505119, 'bagging_fraction': 0.9879480249010957, 'bagging_freq': 20, 'min_child_samples': 3000, 'min_data_in_leaf': 61, 'lambda_l1': 0.03693618420138518, 'lambda_l2': 0.01127107959395742, 'min_gain_to_split': 0.010284974583145517}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:53:26,290] Trial 12 finished with value: 0.40091291490431036 and parameters: {'learning_rate': 0.030420479437036577, 'num_leaves': 114, 'max_depth': 45, 'feature_fraction': 0.9959279705120211, 'bagging_fraction': 0.9963238049957398, 'bagging_freq': 20, 'min_child_samples': 2995, 'min_data_in_leaf': 57, 'lambda_l1': 0.027598453090803547, 'lambda_l2': 0.010968254133761903, 'min_gain_to_split': 0.010017132889452092}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:53:52,656] Trial 13 finished with value: 0.4073371429381526 and parameters: {'learning_rate': 0.03497017775566491, 'num_leaves': 132, 'max_depth': 50, 'feature_fraction': 0.9954441641642936, 'bagging_fraction': 0.9179361505017093, 'bagging_freq': 20, 'min_child_samples': 2903, 'min_data_in_leaf': 41, 'lambda_l1': 0.08546211211044649, 'lambda_l2': 0.010245479718550736, 'min_gain_to_split': 0.011126545967738877}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:54:05,469] Trial 14 finished with value: 0.39731332855264767 and parameters: {'learning_rate': 0.09960464122331925, 'num_leaves': 140, 'max_depth': 51, 'feature_fraction': 0.8899329951885564, 'bagging_fraction': 0.9056980896775906, 'bagging_freq': 21, 'min_child_samples': 2702, 'min_data_in_leaf': 40, 'lambda_l1': 0.09525587248748407, 'lambda_l2': 0.01765258245394763, 'min_gain_to_split': 0.013037019735516586}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:54:22,753] Trial 15 finished with value: 0.40154665346057616 and parameters: {'learning_rate': 0.03709944708658423, 'num_leaves': 137, 'max_depth': 51, 'feature_fraction': 0.9990895088924131, 'bagging_fraction': 0.9151125303512839, 'bagging_freq': 23, 'min_child_samples': 2689, 'min_data_in_leaf': 40, 'lambda_l1': 0.09145413430964038, 'lambda_l2': 0.05799753658241903, 'min_gain_to_split': 0.0550847971295903}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:54:44,517] Trial 16 finished with value: 0.39329499899338394 and parameters: {'learning_rate': 0.0365890744898959, 'num_leaves': 132, 'max_depth': 51, 'feature_fraction': 0.7766387837262839, 'bagging_fraction': 0.8988864685652653, 'bagging_freq': 18, 'min_child_samples': 2786, 'min_data_in_leaf': 51, 'lambda_l1': 0.00452353523693292, 'lambda_l2': 0.04829056238261734, 'min_gain_to_split': 0.013197113466386622}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),
[I 2026-04-08 12:55:03,664] Trial 17 finished with value: 0.3956700357573587 and parameters: {'learning_rate': 0.038822289240495814, 'num_leaves': 101, 'max_depth': 41, 'feature_fraction': 0.8926124493291724, 'bagging_fraction': 0.9549691272466891, 'bagging_freq': 26, 'min_child_samples': 1520, 'min_data_in_leaf': 76, 'lambda_l1': 0.024704584039979098, 'lambda_l2': 0.01707034627656669, 'min_gain_to_split': 0.01510541881788222}. Best is trial 10 with value: 0.4076755677426138.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\2282963097.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 100, 1),

--- ¡Optimización Terminada! ---
Mejor Score Kappa (OOF): 0.4141
Mejores Hiperparámetros encontrados:
    'learning_rate': 0.06979818452348317
    'num_leaves': 233
    'max_depth': 60
    'feature_fraction': 0.9165132580606841
    'bagging_fraction': 0.9892359436440317
    'bagging_freq': 18
    'min_child_samples': 1531
    'min_data_in_leaf': 47
    'lambda_l1': 0.011349471900716017
    'lambda_l2': 0.013799677385552779
    'min_gain_to_split': 0.010447860690942043

In [105]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.8, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 200, 270),
        'max_depth': trial.suggest_int('max_depth', 50, 80),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.85, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.85, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 15, 25),
        'min_child_samples': trial.suggest_int('min_child_samples', 1000, 2000),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.025, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.005,0.05, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.07, 0.15, log=True), # Peaje más caro para abrir ramas 
    }
    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=1000)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-08 23:39:31,606] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:39:45,568] Trial 0 finished with value: 0.39902299647791395 and parameters: {'learning_rate': 0.0711488277092433, 'num_leaves': 218, 'max_depth': 62, 'feature_fraction': 0.905214937314951, 'bagging_fraction': 0.9992312517553792, 'bagging_freq': 16, 'min_child_samples': 1919, 'min_data_in_leaf': 60, 'lambda_l1': 0.011561735792353929, 'lambda_l2': 0.02109902502736927, 'min_gain_to_split': 0.14727245345076584}. Best is trial 0 with value: 0.39902299647791395.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:39:55,641] Trial 1 finished with value: 0.39834695747551363 and parameters: {'learning_rate': 0.1326510713174819, 'num_leaves': 204, 'max_depth': 73, 'feature_fraction': 0.8883339519415955, 'bagging_fraction': 0.9587935604962943, 'bagging_freq': 15, 'min_child_samples': 1063, 'min_data_in_leaf': 57, 'lambda_l1': 0.01993096604128101, 'lambda_l2': 0.008334553956239431, 'min_gain_to_split': 0.14735959897030024}. Best is trial 0 with value: 0.39902299647791395.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:40:04,849] Trial 2 finished with value: 0.4039084264936914 and parameters: {'learning_rate': 0.22979831710825274, 'num_leaves': 223, 'max_depth': 63, 'feature_fraction': 0.9183866861812702, 'bagging_fraction': 0.958719999754075, 'bagging_freq': 23, 'min_child_samples': 1820, 'min_data_in_leaf': 49, 'lambda_l1': 0.0038047548647891943, 'lambda_l2': 0.03393503276437496, 'min_gain_to_split': 0.14705998543360513}. Best is trial 2 with value: 0.4039084264936914.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:40:13,094] Trial 3 finished with value: 0.3634614257246571 and parameters: {'learning_rate': 0.661831086863658, 'num_leaves': 205, 'max_depth': 54, 'feature_fraction': 0.8517830588420957, 'bagging_fraction': 0.9794017129769041, 'bagging_freq': 16, 'min_child_samples': 1625, 'min_data_in_leaf': 51, 'lambda_l1': 0.008976146283493839, 'lambda_l2': 0.006375144209058889, 'min_gain_to_split': 0.07697087661402685}. Best is trial 2 with value: 0.4039084264936914.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:40:31,479] Trial 4 finished with value: 0.40776507680802865 and parameters: {'learning_rate': 0.11187653114144673, 'num_leaves': 251, 'max_depth': 55, 'feature_fraction': 0.8656414007520045, 'bagging_fraction': 0.8553465620920608, 'bagging_freq': 23, 'min_child_samples': 1086, 'min_data_in_leaf': 52, 'lambda_l1': 0.004461815878409228, 'lambda_l2': 0.02283569263034307, 'min_gain_to_split': 0.10007391586241551}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:40:39,269] Trial 5 finished with value: 0.3715986080590883 and parameters: {'learning_rate': 0.6540077219025806, 'num_leaves': 240, 'max_depth': 55, 'feature_fraction': 0.9041855889982175, 'bagging_fraction': 0.9688439776579721, 'bagging_freq': 15, 'min_child_samples': 1625, 'min_data_in_leaf': 52, 'lambda_l1': 0.002514409228403712, 'lambda_l2': 0.03947446235533269, 'min_gain_to_split': 0.13757881616018008}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:40:56,936] Trial 6 finished with value: 0.3909497147979085 and parameters: {'learning_rate': 0.08829872682467804, 'num_leaves': 212, 'max_depth': 60, 'feature_fraction': 0.8746520161628115, 'bagging_fraction': 0.9358833845913033, 'bagging_freq': 23, 'min_child_samples': 1288, 'min_data_in_leaf': 41, 'lambda_l1': 0.002935114453454172, 'lambda_l2': 0.030200992798570206, 'min_gain_to_split': 0.1418931995234081}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:41:06,861] Trial 7 finished with value: 0.3822751931297038 and parameters: {'learning_rate': 0.3937949983863774, 'num_leaves': 263, 'max_depth': 59, 'feature_fraction': 0.8849347570794637, 'bagging_fraction': 0.9273755817246158, 'bagging_freq': 24, 'min_child_samples': 1434, 'min_data_in_leaf': 57, 'lambda_l1': 0.0024601443576657556, 'lambda_l2': 0.010106424965451955, 'min_gain_to_split': 0.14371525027151402}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:41:19,649] Trial 8 finished with value: 0.39624469337495316 and parameters: {'learning_rate': 0.20187344641026583, 'num_leaves': 259, 'max_depth': 73, 'feature_fraction': 0.9781597475514753, 'bagging_fraction': 0.8947717269171184, 'bagging_freq': 21, 'min_child_samples': 1829, 'min_data_in_leaf': 52, 'lambda_l1': 0.0011506748570541611, 'lambda_l2': 0.011027111459185945, 'min_gain_to_split': 0.13586380255516842}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:41:36,501] Trial 9 finished with value: 0.40021370261098055 and parameters: {'learning_rate': 0.06346667254297976, 'num_leaves': 219, 'max_depth': 64, 'feature_fraction': 0.9352553408315211, 'bagging_fraction': 0.9906383736725936, 'bagging_freq': 18, 'min_child_samples': 1865, 'min_data_in_leaf': 58, 'lambda_l1': 0.008959186667987775, 'lambda_l2': 0.021269297809395633, 'min_gain_to_split': 0.07436693371211359}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:41:49,517] Trial 10 finished with value: 0.39470507253986964 and parameters: {'learning_rate': 0.12215453275455095, 'num_leaves': 246, 'max_depth': 51, 'feature_fraction': 0.9485344194283699, 'bagging_fraction': 0.8516789582690009, 'bagging_freq': 21, 'min_child_samples': 1069, 'min_data_in_leaf': 45, 'lambda_l1': 0.0012675813541122816, 'lambda_l2': 0.015970534617069883, 'min_gain_to_split': 0.10217274019705626}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:41:57,881] Trial 11 finished with value: 0.4002390856580351 and parameters: {'learning_rate': 0.26287760180361097, 'num_leaves': 227, 'max_depth': 67, 'feature_fraction': 0.8508207521557016, 'bagging_fraction': 0.8873296157781235, 'bagging_freq': 25, 'min_child_samples': 1332, 'min_data_in_leaf': 47, 'lambda_l1': 0.004687161045683206, 'lambda_l2': 0.047668974169175565, 'min_gain_to_split': 0.10844448085788391}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:42:06,619] Trial 12 finished with value: 0.3801604833209864 and parameters: {'learning_rate': 0.32155494273924107, 'num_leaves': 252, 'max_depth': 68, 'feature_fraction': 0.9692035085117598, 'bagging_fraction': 0.8500061545480837, 'bagging_freq': 22, 'min_child_samples': 1696, 'min_data_in_leaf': 47, 'lambda_l1': 0.004353314603936801, 'lambda_l2': 0.02800707996270865, 'min_gain_to_split': 0.10097903228943167}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:42:19,515] Trial 13 finished with value: 0.40101414890443976 and parameters: {'learning_rate': 0.1392526163093948, 'num_leaves': 230, 'max_depth': 79, 'feature_fraction': 0.9177313161247526, 'bagging_fraction': 0.8963827296580957, 'bagging_freq': 19, 'min_child_samples': 1230, 'min_data_in_leaf': 55, 'lambda_l1': 0.006205082418209524, 'lambda_l2': 0.031128680085538436, 'min_gain_to_split': 0.11633577680318784}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:42:31,471] Trial 14 finished with value: 0.3890930610840658 and parameters: {'learning_rate': 0.19717769088940867, 'num_leaves': 238, 'max_depth': 56, 'feature_fraction': 0.9967863764424756, 'bagging_fraction': 0.9529663682307578, 'bagging_freq': 25, 'min_child_samples': 2000, 'min_data_in_leaf': 48, 'lambda_l1': 0.001745076232429352, 'lambda_l2': 0.01681739533720138, 'min_gain_to_split': 0.08569085683089031}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:42:49,588] Trial 15 finished with value: 0.39938825192020655 and parameters: {'learning_rate': 0.09755544222619911, 'num_leaves': 268, 'max_depth': 50, 'feature_fraction': 0.9443642021572357, 'bagging_fraction': 0.8773317955508119, 'bagging_freq': 23, 'min_child_samples': 1476, 'min_data_in_leaf': 43, 'lambda_l1': 0.003657589001791337, 'lambda_l2': 0.0225470699272367, 'min_gain_to_split': 0.08702253090566016}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:43:04,590] Trial 16 finished with value: 0.4021806246421833 and parameters: {'learning_rate': 0.05176068289272181, 'num_leaves': 251, 'max_depth': 71, 'feature_fraction': 0.865519163151576, 'bagging_fraction': 0.9090587495562346, 'bagging_freq': 20, 'min_child_samples': 1751, 'min_data_in_leaf': 54, 'lambda_l1': 0.00594765877023352, 'lambda_l2': 0.04091768211222751, 'min_gain_to_split': 0.12436703951352648}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),
[I 2026-04-08 23:43:15,396] Trial 17 finished with value: 0.3941476488432982 and parameters: {'learning_rate': 0.1835497870732924, 'num_leaves': 226, 'max_depth': 58, 'feature_fraction': 0.9179764326358874, 'bagging_fraction': 0.9400954529171468, 'bagging_freq': 23, 'min_child_samples': 1166, 'min_data_in_leaf': 50, 'lambda_l1': 0.0018408123488400847, 'lambda_l2': 0.013094427337012436, 'min_gain_to_split': 0.09239477879533074}. Best is trial 4 with value: 0.40776507680802865.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\3606145962.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 40, 60, 1),

--- ¡Optimización Terminada! ---
Mejor Score Kappa (OOF): 0.4147
Mejores Hiperparámetros encontrados:
    'learning_rate': 0.10757105093289668
    'num_leaves': 213
    'max_depth': 76
    'feature_fraction': 0.8844720212991225
    'bagging_fraction': 0.9248376103423376
    'bagging_freq': 23
    'min_child_samples': 1029
    'min_data_in_leaf': 58
    'lambda_l1': 0.0010129469093082858
    'lambda_l2': 0.02128555488699726
    'min_gain_to_split': 0.09951613060656529

In [106]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 200, 240),
        'max_depth': trial.suggest_int('max_depth', 35, 80),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.86, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.86, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 17, 24),
        'min_child_samples': trial.suggest_int('min_child_samples', 1000, 1800, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.01, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.005,0.025, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.07, 0.13, log=True), # Peaje más caro para abrir ramas 
    }

'learning_rate': 0.06944835999597897, 
'num_leaves': 213, 
'max_depth': 37, 
'feature_fraction': 0.872345644337963, 
'bagging_fraction': 0.965774173133069, 
'bagging_freq': 19, 
'min_child_samples': 1298, 
'min_data_in_leaf': 57, 
'lambda_l1': 0.006012766850092706, 
'lambda_l2': 0.008100955457339194, 
'min_gain_to_split': 0.07198419292196633

    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=500)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-09 08:22:46,221] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:22:54,496] Trial 0 finished with value: 0.3973338303173921 and parameters: {'learning_rate': 0.07528814817438165, 'num_leaves': 233, 'max_depth': 40, 'feature_fraction': 0.8899962563322092, 'bagging_fraction': 0.9994906452688412, 'bagging_freq': 23, 'min_child_samples': 1164, 'min_data_in_leaf': 45, 'lambda_l1': 0.0037561442631910127, 'lambda_l2': 0.02348513508304213, 'min_gain_to_split': 0.10203313369496127}. Best is trial 0 with value: 0.3973338303173921.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:00,385] Trial 1 finished with value: 0.39784139287616704 and parameters: {'learning_rate': 0.17992651204674143, 'num_leaves': 237, 'max_depth': 50, 'feature_fraction': 0.9758489926328556, 'bagging_fraction': 0.9215801973037694, 'bagging_freq': 22, 'min_child_samples': 1519, 'min_data_in_leaf': 53, 'lambda_l1': 0.007757877866943157, 'lambda_l2': 0.006531150347360781, 'min_gain_to_split': 0.0906015697120376}. Best is trial 1 with value: 0.39784139287616704.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:06,751] Trial 2 finished with value: 0.38818865235679456 and parameters: {'learning_rate': 0.18183768332724215, 'num_leaves': 230, 'max_depth': 44, 'feature_fraction': 0.8738309415100693, 'bagging_fraction': 0.9144907495248563, 'bagging_freq': 23, 'min_child_samples': 1274, 'min_data_in_leaf': 60, 'lambda_l1': 0.008883792385344147, 'lambda_l2': 0.020989924352679407, 'min_gain_to_split': 0.07742117756283337}. Best is trial 1 with value: 0.39784139287616704.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:16,997] Trial 3 finished with value: 0.40275476074800776 and parameters: {'learning_rate': 0.05865526532669274, 'num_leaves': 208, 'max_depth': 69, 'feature_fraction': 0.8692939730098126, 'bagging_fraction': 0.9411558222663821, 'bagging_freq': 21, 'min_child_samples': 1262, 'min_data_in_leaf': 56, 'lambda_l1': 0.0013376583667059282, 'lambda_l2': 0.007943922556004493, 'min_gain_to_split': 0.11284312504986688}. Best is trial 3 with value: 0.40275476074800776.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:26,496] Trial 4 finished with value: 0.4044475850451611 and parameters: {'learning_rate': 0.07930736241460185, 'num_leaves': 201, 'max_depth': 64, 'feature_fraction': 0.9058887436352954, 'bagging_fraction': 0.9214527071834011, 'bagging_freq': 24, 'min_child_samples': 1456, 'min_data_in_leaf': 52, 'lambda_l1': 0.005095380105881646, 'lambda_l2': 0.0167400087263794, 'min_gain_to_split': 0.09323774487239728}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:34,495] Trial 5 finished with value: 0.39929226917095806 and parameters: {'learning_rate': 0.07697716933018853, 'num_leaves': 216, 'max_depth': 63, 'feature_fraction': 0.9479695279399754, 'bagging_fraction': 0.8905227983520598, 'bagging_freq': 17, 'min_child_samples': 1172, 'min_data_in_leaf': 52, 'lambda_l1': 0.0054038580850393255, 'lambda_l2': 0.006857868507679349, 'min_gain_to_split': 0.12848455420430477}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:41,554] Trial 6 finished with value: 0.3966411223633115 and parameters: {'learning_rate': 0.13594446297673757, 'num_leaves': 236, 'max_depth': 50, 'feature_fraction': 0.9542378529147699, 'bagging_fraction': 0.890836454440254, 'bagging_freq': 18, 'min_child_samples': 1161, 'min_data_in_leaf': 59, 'lambda_l1': 0.0019641854499258906, 'lambda_l2': 0.01070604076739814, 'min_gain_to_split': 0.0956810082241761}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:49,422] Trial 7 finished with value: 0.39959083272623186 and parameters: {'learning_rate': 0.05624447255613814, 'num_leaves': 219, 'max_depth': 50, 'feature_fraction': 0.980030022859592, 'bagging_fraction': 0.965907562640516, 'bagging_freq': 18, 'min_child_samples': 1025, 'min_data_in_leaf': 56, 'lambda_l1': 0.001397441302478472, 'lambda_l2': 0.01642196290873175, 'min_gain_to_split': 0.07120391473808074}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:23:56,680] Trial 8 finished with value: 0.40133392645765886 and parameters: {'learning_rate': 0.09222621313037645, 'num_leaves': 202, 'max_depth': 52, 'feature_fraction': 0.8683099214565965, 'bagging_fraction': 0.9962648297078699, 'bagging_freq': 18, 'min_child_samples': 1628, 'min_data_in_leaf': 54, 'lambda_l1': 0.0030367046231855425, 'lambda_l2': 0.008785958860144535, 'min_gain_to_split': 0.0984726881940445}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:03,420] Trial 9 finished with value: 0.3985636004952874 and parameters: {'learning_rate': 0.1185755973662809, 'num_leaves': 211, 'max_depth': 56, 'feature_fraction': 0.9762796244514621, 'bagging_fraction': 0.9320799468472121, 'bagging_freq': 22, 'min_child_samples': 1340, 'min_data_in_leaf': 55, 'lambda_l1': 0.007217710973975928, 'lambda_l2': 0.005878634581410907, 'min_gain_to_split': 0.08971414445021633}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:10,163] Trial 10 finished with value: 0.3989510124484419 and parameters: {'learning_rate': 0.09453615714916247, 'num_leaves': 203, 'max_depth': 75, 'feature_fraction': 0.9058775893709874, 'bagging_fraction': 0.8637587406034659, 'bagging_freq': 24, 'min_child_samples': 1759, 'min_data_in_leaf': 49, 'lambda_l1': 0.003644460453129637, 'lambda_l2': 0.014782276384994575, 'min_gain_to_split': 0.08254802674430227}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:20,120] Trial 11 finished with value: 0.40048403959577994 and parameters: {'learning_rate': 0.05165903971653009, 'num_leaves': 209, 'max_depth': 68, 'feature_fraction': 0.9139631786820446, 'bagging_fraction': 0.9505115756698379, 'bagging_freq': 20, 'min_child_samples': 1475, 'min_data_in_leaf': 50, 'lambda_l1': 0.0010323520152511786, 'lambda_l2': 0.013743430233291559, 'min_gain_to_split': 0.11366945922871312}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:29,498] Trial 12 finished with value: 0.4029590399608092 and parameters: {'learning_rate': 0.06531521176555423, 'num_leaves': 201, 'max_depth': 80, 'feature_fraction': 0.89385997817226, 'bagging_fraction': 0.956394162368339, 'bagging_freq': 21, 'min_child_samples': 1431, 'min_data_in_leaf': 58, 'lambda_l1': 0.0023177894033806737, 'lambda_l2': 0.009134765827066956, 'min_gain_to_split': 0.11370378920403676}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:38,841] Trial 13 finished with value: 0.3967527950865477 and parameters: {'learning_rate': 0.07126760991648655, 'num_leaves': 200, 'max_depth': 80, 'feature_fraction': 0.9247880916355417, 'bagging_fraction': 0.9708563359572732, 'bagging_freq': 20, 'min_child_samples': 1475, 'min_data_in_leaf': 58, 'lambda_l1': 0.002312573384254455, 'lambda_l2': 0.010628359610517842, 'min_gain_to_split': 0.10916864349633199}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:48,993] Trial 14 finished with value: 0.4035056796520885 and parameters: {'learning_rate': 0.06611985060236192, 'num_leaves': 226, 'max_depth': 64, 'feature_fraction': 0.8933215314094978, 'bagging_fraction': 0.9587146153489315, 'bagging_freq': 24, 'min_child_samples': 1408, 'min_data_in_leaf': 50, 'lambda_l1': 0.004830677575512364, 'lambda_l2': 0.01946580337251865, 'min_gain_to_split': 0.11839308341777091}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:24:56,967] Trial 15 finished with value: 0.3998117542010178 and parameters: {'learning_rate': 0.08659283137333468, 'num_leaves': 226, 'max_depth': 62, 'feature_fraction': 0.9435051373082614, 'bagging_fraction': 0.9086205821056613, 'bagging_freq': 24, 'min_child_samples': 1595, 'min_data_in_leaf': 48, 'lambda_l1': 0.005233328964525191, 'lambda_l2': 0.01751503572947693, 'min_gain_to_split': 0.1282494970576622}. Best is trial 4 with value: 0.4044475850451611.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:25:04,844] Trial 16 finished with value: 0.40563884387123217 and parameters: {'learning_rate': 0.12919837488981356, 'num_leaves': 225, 'max_depth': 62, 'feature_fraction': 0.8907662193754025, 'bagging_fraction': 0.9829962252064272, 'bagging_freq': 24, 'min_child_samples': 1352, 'min_data_in_leaf': 51, 'lambda_l1': 0.005202953160156441, 'lambda_l2': 0.019603470107690493, 'min_gain_to_split': 0.08507608145969837}. Best is trial 16 with value: 0.40563884387123217.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),
[I 2026-04-09 08:25:11,635] Trial 17 finished with value: 0.4046588229402269 and parameters: {'learning_rate': 0.11677292498153041, 'num_leaves': 223, 'max_depth': 58, 'feature_fraction': 0.9252405045970276, 'bagging_fraction': 0.9784094382264104, 'bagging_freq': 23, 'min_child_samples': 1351, 'min_data_in_leaf': 47, 'lambda_l1': 0.006530012697011215, 'lambda_l2': 0.013333529298880865, 'min_gain_to_split': 0.08470453900768427}. Best is trial 16 with value: 0.40563884387123217.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1284922978.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 45, 60, 1),

--- ¡Optimización Terminada! ---
Mejor Score Kappa (OOF): 0.4154
Mejores Hiperparámetros encontrados:
    'learning_rate': 0.06944835999597897
    'num_leaves': 213
    'max_depth': 37
    'feature_fraction': 0.872345644337963
    'bagging_fraction': 0.965774173133069
    'bagging_freq': 19
    'min_child_samples': 1298
    'min_data_in_leaf': 57
    'lambda_l1': 0.006012766850092706
    'lambda_l2': 0.008100955457339194
    'min_gain_to_split': 0.07198419292196633

In [ ]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.05, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 200, 230),
        'max_depth': trial.suggest_int('max_depth', 35, 45),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.86, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.95, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 17, 24),
        'min_child_samples': trial.suggest_int('min_child_samples', 1000, 1500, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.005, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.005,0.012, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.06, 0.1, log=True), # Peaje más caro para abrir ramas 
    }

    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=500)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-09 10:19:25,825] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:19:37,788] Trial 0 finished with value: 0.4024105536963525 and parameters: {'learning_rate': 0.054258391411151484, 'num_leaves': 220, 'max_depth': 39, 'feature_fraction': 0.9681054478654658, 'bagging_fraction': 0.9535983066268133, 'bagging_freq': 24, 'min_child_samples': 1252, 'min_data_in_leaf': 54, 'lambda_l1': 0.002866298021326141, 'lambda_l2': 0.009065459631746372, 'min_gain_to_split': 0.0668300206216683}. Best is trial 0 with value: 0.4024105536963525.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:19:50,150] Trial 1 finished with value: 0.3968105275584807 and parameters: {'learning_rate': 0.05439568778582323, 'num_leaves': 216, 'max_depth': 36, 'feature_fraction': 0.9654367660402565, 'bagging_fraction': 0.997323595200156, 'bagging_freq': 24, 'min_child_samples': 1180, 'min_data_in_leaf': 60, 'lambda_l1': 0.0016849555715424318, 'lambda_l2': 0.006498648690096278, 'min_gain_to_split': 0.08908662978545662}. Best is trial 0 with value: 0.4024105536963525.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:20:05,278] Trial 2 finished with value: 0.39993608825913307 and parameters: {'learning_rate': 0.05314495306572508, 'num_leaves': 200, 'max_depth': 35, 'feature_fraction': 0.9146231960808465, 'bagging_fraction': 0.9519093226235691, 'bagging_freq': 23, 'min_child_samples': 1021, 'min_data_in_leaf': 52, 'lambda_l1': 0.004073844642868228, 'lambda_l2': 0.006123794466004489, 'min_gain_to_split': 0.0714192094739581}. Best is trial 0 with value: 0.4024105536963525.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:20:17,708] Trial 3 finished with value: 0.40946359505013963 and parameters: {'learning_rate': 0.09317300167018468, 'num_leaves': 213, 'max_depth': 38, 'feature_fraction': 0.9838827616753838, 'bagging_fraction': 0.9572029675956578, 'bagging_freq': 17, 'min_child_samples': 1209, 'min_data_in_leaf': 54, 'lambda_l1': 0.0010878105117556375, 'lambda_l2': 0.005409364927822257, 'min_gain_to_split': 0.06937655222892941}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:20:33,135] Trial 4 finished with value: 0.40237065344064693 and parameters: {'learning_rate': 0.06037504405313588, 'num_leaves': 212, 'max_depth': 36, 'feature_fraction': 0.9507532392429062, 'bagging_fraction': 0.9954877192555589, 'bagging_freq': 20, 'min_child_samples': 1280, 'min_data_in_leaf': 58, 'lambda_l1': 0.0016187275733455463, 'lambda_l2': 0.009640548059553168, 'min_gain_to_split': 0.07147160331619216}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:20:54,305] Trial 5 finished with value: 0.40711140867386775 and parameters: {'learning_rate': 0.06162856598266343, 'num_leaves': 222, 'max_depth': 37, 'feature_fraction': 0.9260901152137464, 'bagging_fraction': 0.987816163570628, 'bagging_freq': 23, 'min_child_samples': 1008, 'min_data_in_leaf': 61, 'lambda_l1': 0.0029456013239461476, 'lambda_l2': 0.006571770990862983, 'min_gain_to_split': 0.0642482728382497}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:21:14,032] Trial 6 finished with value: 0.40428475704268607 and parameters: {'learning_rate': 0.06349249275478824, 'num_leaves': 221, 'max_depth': 37, 'feature_fraction': 0.9074586148000945, 'bagging_fraction': 0.9666821408654055, 'bagging_freq': 23, 'min_child_samples': 1435, 'min_data_in_leaf': 60, 'lambda_l1': 0.004167896387498292, 'lambda_l2': 0.006477879132894814, 'min_gain_to_split': 0.06403087848305054}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:21:33,088] Trial 7 finished with value: 0.40131523723819607 and parameters: {'learning_rate': 0.05268538836511145, 'num_leaves': 210, 'max_depth': 38, 'feature_fraction': 0.9948484158934867, 'bagging_fraction': 0.9609866417293642, 'bagging_freq': 17, 'min_child_samples': 1236, 'min_data_in_leaf': 56, 'lambda_l1': 0.0015307749534765743, 'lambda_l2': 0.005314972361454673, 'min_gain_to_split': 0.0741094084383372}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:21:51,986] Trial 8 finished with value: 0.4036773100130324 and parameters: {'learning_rate': 0.06501481971213173, 'num_leaves': 226, 'max_depth': 37, 'feature_fraction': 0.9976920859626889, 'bagging_fraction': 0.9836569452147943, 'bagging_freq': 23, 'min_child_samples': 1364, 'min_data_in_leaf': 56, 'lambda_l1': 0.001093564474513705, 'lambda_l2': 0.007423758309865345, 'min_gain_to_split': 0.06658559903117087}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:22:06,176] Trial 9 finished with value: 0.4031683794046521 and parameters: {'learning_rate': 0.08342005479296123, 'num_leaves': 217, 'max_depth': 38, 'feature_fraction': 0.9126330068049623, 'bagging_fraction': 0.9940611610025251, 'bagging_freq': 21, 'min_child_samples': 1439, 'min_data_in_leaf': 57, 'lambda_l1': 0.0013148760959673662, 'lambda_l2': 0.010757419815050797, 'min_gain_to_split': 0.06434326216422798}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:22:22,640] Trial 10 finished with value: 0.40036033473699606 and parameters: {'learning_rate': 0.09809794547119012, 'num_leaves': 206, 'max_depth': 42, 'feature_fraction': 0.863056683142681, 'bagging_fraction': 0.9680286195367539, 'bagging_freq': 17, 'min_child_samples': 1133, 'min_data_in_leaf': 51, 'lambda_l1': 0.0021937646069953875, 'lambda_l2': 0.005221995174357814, 'min_gain_to_split': 0.085586533926879}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:22:41,056] Trial 11 finished with value: 0.3971862023378495 and parameters: {'learning_rate': 0.07899396343452808, 'num_leaves': 230, 'max_depth': 41, 'feature_fraction': 0.9391403486256334, 'bagging_fraction': 0.9818860928127785, 'bagging_freq': 19, 'min_child_samples': 1005, 'min_data_in_leaf': 54, 'lambda_l1': 0.0026589727134981225, 'lambda_l2': 0.007536778712035391, 'min_gain_to_split': 0.06028072197339259}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:22:59,796] Trial 12 finished with value: 0.4019396326532635 and parameters: {'learning_rate': 0.09960959383991833, 'num_leaves': 222, 'max_depth': 40, 'feature_fraction': 0.8714237454534648, 'bagging_fraction': 0.9826329216497142, 'bagging_freq': 21, 'min_child_samples': 1090, 'min_data_in_leaf': 61, 'lambda_l1': 0.0029403700619016968, 'lambda_l2': 0.005669023409978873, 'min_gain_to_split': 0.07958387581434799}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:23:17,035] Trial 13 finished with value: 0.40381969882150415 and parameters: {'learning_rate': 0.07283492641160148, 'num_leaves': 208, 'max_depth': 43, 'feature_fraction': 0.8903330856973652, 'bagging_fraction': 0.9747435590358335, 'bagging_freq': 19, 'min_child_samples': 1075, 'min_data_in_leaf': 54, 'lambda_l1': 0.002149503981671148, 'lambda_l2': 0.006912291178958209, 'min_gain_to_split': 0.0785025314087114}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:23:32,409] Trial 14 finished with value: 0.4049252568016499 and parameters: {'learning_rate': 0.08921478298362905, 'num_leaves': 214, 'max_depth': 40, 'feature_fraction': 0.9318571774290655, 'bagging_fraction': 0.9889914471728499, 'bagging_freq': 18, 'min_child_samples': 1334, 'min_data_in_leaf': 58, 'lambda_l1': 0.001133986237616133, 'lambda_l2': 0.005008219312186096, 'min_gain_to_split': 0.09618004161381029}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:23:47,959] Trial 15 finished with value: 0.3990333158223466 and parameters: {'learning_rate': 0.07254407054266275, 'num_leaves': 225, 'max_depth': 35, 'feature_fraction': 0.9751249432417722, 'bagging_fraction': 0.9733097868034661, 'bagging_freq': 22, 'min_child_samples': 1162, 'min_data_in_leaf': 53, 'lambda_l1': 0.0035015803014193155, 'lambda_l2': 0.005917483203871589, 'min_gain_to_split': 0.06200232144841127}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:24:05,685] Trial 16 finished with value: 0.4033620150613949 and parameters: {'learning_rate': 0.059300120734888176, 'num_leaves': 205, 'max_depth': 45, 'feature_fraction': 0.9405351702733739, 'bagging_fraction': 0.9599415149551774, 'bagging_freq': 20, 'min_child_samples': 1065, 'min_data_in_leaf': 59, 'lambda_l1': 0.004961889177155168, 'lambda_l2': 0.0085214218407171, 'min_gain_to_split': 0.06921283216325672}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),
[I 2026-04-09 10:24:25,650] Trial 17 finished with value: 0.4072412936658193 and parameters: {'learning_rate': 0.06906277133013301, 'num_leaves': 218, 'max_depth': 38, 'feature_fraction': 0.9524822673573247, 'bagging_fraction': 0.988329531949732, 'bagging_freq': 22, 'min_child_samples': 1495, 'min_data_in_leaf': 55, 'lambda_l1': 0.0019167738962065845, 'lambda_l2': 0.008154745083558923, 'min_gain_to_split': 0.07505362968453917}. Best is trial 3 with value: 0.40946359505013963.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1601356527.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 51, 61, 1),

--- ¡Optimización Terminada! ---
Mejor Score Kappa (OOF): 0.4155
Mejores Hiperparámetros encontrados:
    'learning_rate': 0.08971210430879904
    'num_leaves': 209
    'max_depth': 36
    'feature_fraction': 0.8980577412306568
    'bagging_fraction': 0.9888816790376405
    'bagging_freq': 17
    'min_child_samples': 1010
    'min_data_in_leaf': 61
    'lambda_l1': 0.0020519474560541156
    'lambda_l2': 0.005919979899030505
    'min_gain_to_split': 0.06505635341081556

In [ ]:
import optuna
import lightgbm as lgb
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import cohen_kappa_score

# Asegúrate de tener X_train, y_train y categorical_cols definidos previamente

def objective(trial):
    # 1. Definir el espacio de búsqueda de hiperparámetros
    param = {
        'objective': 'multiclass',
        'num_class': 5,
        'metric': 'multi_error',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'seed': 42,

        # Hiperparámetros a optimizar por Optuna
        'learning_rate': trial.suggest_float('learning_rate', 0.07, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 200, 230),
        'max_depth': trial.suggest_int('max_depth', 35, 40),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.86, 0.90),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.95, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 17, 20),
        'min_child_samples': trial.suggest_int('min_child_samples', 1000, 1100, log=True),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
        'lambda_l1': trial.suggest_float('lambda_l1',0.001,0.003, log=True),
        'lambda_l2': trial.suggest_float('lambda_l2',0.005,0.01, log=True),
        'min_gain_to_split':    trial.suggest_float('min_gain_to_split', 0.06, 0.08, log=True), # Peaje más caro para abrir ramas 
    }

    # 2. Configurar la Validación Cruzada
    N_SPLITS = 5
    folds = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)
    oof_preds = np.zeros((len(X_train), 5))

    # 3. Bucle de entrenamiento por Fold
    for fold_, (trn_idx, val_idx) in enumerate(folds.split(X_train, y_train)):
        X_tr, y_tr = X_train.iloc[trn_idx], y_train.iloc[trn_idx]
        X_val, y_val = X_train.iloc[val_idx], y_train.iloc[val_idx]
        
        trn_data = lgb.Dataset(X_tr, label=y_tr, categorical_feature=categorical_cols)
        val_data = lgb.Dataset(X_val, label=y_val, categorical_feature=categorical_cols, reference=trn_data)
        
        # Entrenar el modelo
        clf = lgb.train(
            param,
            trn_data,
            num_boost_round=500, # Un número alto, early_stopping lo detendrá antes
            valid_sets=[trn_data, val_data],
            callbacks=[
                lgb.early_stopping(stopping_rounds=30, verbose=False)
            ]
        )
        
        # Guardar predicciones de validación
        oof_preds[val_idx] = clf.predict(X_val, num_iteration=clf.best_iteration)

    # 4. Calcular la métrica final (QWK) para este Trial
    oof_predictions_classes = oof_preds.argmax(axis=1)
    kappa_score = cohen_kappa_score(y_train, oof_predictions_classes, weights='quadratic')
    
    return kappa_score

# --- EJECUCIÓN DE LA OPTIMIZACIÓN ---

print("Iniciando búsqueda de hiperparámetros con Optuna...")

# Queremos MAXIMIZAR el score Kappa
study = optuna.create_study(direction='maximize', study_name="Petfinder_LGBM_Optuna")

# Ejecutar el estudio (puedes cambiar n_trials dependiendo del tiempo que tengas)
study.optimize(objective, n_trials=500)

# Mostrar resultados
print("\n--- ¡Optimización Terminada! ---")
print(f"Mejor Score Kappa (OOF): {study.best_value:.4f}")
print("Mejores Hiperparámetros encontrados:")
for key, value in study.best_params.items():
    print(f"    '{key}': {value}")

[I 2026-04-09 13:20:19,549] A new study created in memory with name: Petfinder_LGBM_Optuna

Iniciando búsqueda de hiperparámetros con Optuna...

C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:20:26,825] Trial 0 finished with value: 0.39640020901463235 and parameters: {'learning_rate': 0.07282414684217228, 'num_leaves': 227, 'max_depth': 40, 'feature_fraction': 0.8656358546687993, 'bagging_fraction': 0.9708953630128581, 'bagging_freq': 17, 'min_child_samples': 1019, 'min_data_in_leaf': 62, 'lambda_l1': 0.0012718019479997227, 'lambda_l2': 0.0064267811680307155, 'min_gain_to_split': 0.07299606084467114}. Best is trial 0 with value: 0.39640020901463235.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:20:37,630] Trial 1 finished with value: 0.4057621955604852 and parameters: {'learning_rate': 0.09003099052468763, 'num_leaves': 207, 'max_depth': 39, 'feature_fraction': 0.8786087751915441, 'bagging_fraction': 0.9731928820844562, 'bagging_freq': 18, 'min_child_samples': 1044, 'min_data_in_leaf': 65, 'lambda_l1': 0.0022203941516992973, 'lambda_l2': 0.005739000746157012, 'min_gain_to_split': 0.060366744396897605}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:20:49,327] Trial 2 finished with value: 0.4045812430727914 and parameters: {'learning_rate': 0.07314812698437227, 'num_leaves': 214, 'max_depth': 39, 'feature_fraction': 0.8661186958815946, 'bagging_fraction': 0.9769740317653063, 'bagging_freq': 18, 'min_child_samples': 1017, 'min_data_in_leaf': 61, 'lambda_l1': 0.0010135735817898197, 'lambda_l2': 0.008778547871444796, 'min_gain_to_split': 0.07472636004979855}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:21:02,118] Trial 3 finished with value: 0.40032196175626256 and parameters: {'learning_rate': 0.08235157336505573, 'num_leaves': 223, 'max_depth': 40, 'feature_fraction': 0.8797132297516898, 'bagging_fraction': 0.9925212283216294, 'bagging_freq': 19, 'min_child_samples': 1058, 'min_data_in_leaf': 61, 'lambda_l1': 0.0016642236588077011, 'lambda_l2': 0.0074371619647564885, 'min_gain_to_split': 0.0603619219816489}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:21:13,780] Trial 4 finished with value: 0.4053782731362092 and parameters: {'learning_rate': 0.08181936067447093, 'num_leaves': 211, 'max_depth': 36, 'feature_fraction': 0.8677509472828784, 'bagging_fraction': 0.9551140874120803, 'bagging_freq': 17, 'min_child_samples': 1089, 'min_data_in_leaf': 64, 'lambda_l1': 0.001398906891982693, 'lambda_l2': 0.005158909317041885, 'min_gain_to_split': 0.0636170962649453}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:21:26,284] Trial 5 finished with value: 0.40263045626012084 and parameters: {'learning_rate': 0.08603416363221153, 'num_leaves': 214, 'max_depth': 36, 'feature_fraction': 0.8628870678631432, 'bagging_fraction': 0.9546432731577028, 'bagging_freq': 20, 'min_child_samples': 1062, 'min_data_in_leaf': 63, 'lambda_l1': 0.0014879341322566525, 'lambda_l2': 0.009150820747176887, 'min_gain_to_split': 0.06734035154446365}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:21:41,224] Trial 6 finished with value: 0.40263869460236035 and parameters: {'learning_rate': 0.08991899472070591, 'num_leaves': 202, 'max_depth': 39, 'feature_fraction': 0.8647418748064829, 'bagging_fraction': 0.9823027516465179, 'bagging_freq': 19, 'min_child_samples': 1043, 'min_data_in_leaf': 61, 'lambda_l1': 0.0010378414599061185, 'lambda_l2': 0.005454558956159454, 'min_gain_to_split': 0.06292483437901099}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:21:56,865] Trial 7 finished with value: 0.4038743857380537 and parameters: {'learning_rate': 0.0735089154352148, 'num_leaves': 222, 'max_depth': 39, 'feature_fraction': 0.883585953379467, 'bagging_fraction': 0.9875064370591676, 'bagging_freq': 17, 'min_child_samples': 1094, 'min_data_in_leaf': 61, 'lambda_l1': 0.0010974142610700463, 'lambda_l2': 0.005937066937378204, 'min_gain_to_split': 0.06551969738457462}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:22:10,555] Trial 8 finished with value: 0.40092609114161937 and parameters: {'learning_rate': 0.0838452078179881, 'num_leaves': 212, 'max_depth': 38, 'feature_fraction': 0.8653624433133771, 'bagging_fraction': 0.9659300040022525, 'bagging_freq': 20, 'min_child_samples': 1096, 'min_data_in_leaf': 65, 'lambda_l1': 0.0013174162606618915, 'lambda_l2': 0.005102957941042118, 'min_gain_to_split': 0.06115542857719223}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:22:24,355] Trial 9 finished with value: 0.401891723377124 and parameters: {'learning_rate': 0.0780335679297323, 'num_leaves': 230, 'max_depth': 39, 'feature_fraction': 0.8992116634936759, 'bagging_fraction': 0.972959985508267, 'bagging_freq': 17, 'min_child_samples': 1064, 'min_data_in_leaf': 63, 'lambda_l1': 0.0012918901316368448, 'lambda_l2': 0.00882540320342033, 'min_gain_to_split': 0.06483906925241197}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:22:38,146] Trial 10 finished with value: 0.3994500864824593 and parameters: {'learning_rate': 0.09947334758882519, 'num_leaves': 202, 'max_depth': 37, 'feature_fraction': 0.8784185523819076, 'bagging_fraction': 0.9987946179923043, 'bagging_freq': 18, 'min_child_samples': 1036, 'min_data_in_leaf': 65, 'lambda_l1': 0.002420749828871137, 'lambda_l2': 0.0074454453045642915, 'min_gain_to_split': 0.07992558847326067}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:22:52,522] Trial 11 finished with value: 0.4027936771538151 and parameters: {'learning_rate': 0.09244752556786112, 'num_leaves': 206, 'max_depth': 35, 'feature_fraction': 0.8732730942845156, 'bagging_fraction': 0.9508267025003764, 'bagging_freq': 18, 'min_child_samples': 1080, 'min_data_in_leaf': 64, 'lambda_l1': 0.002155813107779968, 'lambda_l2': 0.0050265130293162, 'min_gain_to_split': 0.06011740339265845}. Best is trial 1 with value: 0.4057621955604852.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:23:13,575] Trial 12 finished with value: 0.4067650391100671 and parameters: {'learning_rate': 0.07906923525545978, 'num_leaves': 209, 'max_depth': 37, 'feature_fraction': 0.888274467781509, 'bagging_fraction': 0.9614783437935053, 'bagging_freq': 17, 'min_child_samples': 1033, 'min_data_in_leaf': 64, 'lambda_l1': 0.00291429566824804, 'lambda_l2': 0.006006042090122533, 'min_gain_to_split': 0.06997773510187093}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:23:33,784] Trial 13 finished with value: 0.40497082709258647 and parameters: {'learning_rate': 0.07795158636391399, 'num_leaves': 207, 'max_depth': 37, 'feature_fraction': 0.8906606496927884, 'bagging_fraction': 0.9629437090972731, 'bagging_freq': 18, 'min_child_samples': 1031, 'min_data_in_leaf': 64, 'lambda_l1': 0.002984336193040633, 'lambda_l2': 0.006305653680828233, 'min_gain_to_split': 0.06990930594922329}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:23:54,118] Trial 14 finished with value: 0.40212250693962215 and parameters: {'learning_rate': 0.09383173790501272, 'num_leaves': 208, 'max_depth': 38, 'feature_fraction': 0.8882079384742674, 'bagging_fraction': 0.962255536836485, 'bagging_freq': 19, 'min_child_samples': 1007, 'min_data_in_leaf': 65, 'lambda_l1': 0.002948724205380444, 'lambda_l2': 0.005782395861001481, 'min_gain_to_split': 0.07053573739285382}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:24:12,903] Trial 15 finished with value: 0.40070099251021984 and parameters: {'learning_rate': 0.08785213651098314, 'num_leaves': 219, 'max_depth': 38, 'feature_fraction': 0.8959724731392569, 'bagging_fraction': 0.9785493997998254, 'bagging_freq': 17, 'min_child_samples': 1048, 'min_data_in_leaf': 64, 'lambda_l1': 0.0021734427228972523, 'lambda_l2': 0.0067679302122826196, 'min_gain_to_split': 0.06748207932817266}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:24:27,860] Trial 16 finished with value: 0.3955836535744064 and parameters: {'learning_rate': 0.0779181530760194, 'num_leaves': 204, 'max_depth': 36, 'feature_fraction': 0.8749080767419042, 'bagging_fraction': 0.9676036250801399, 'bagging_freq': 18, 'min_child_samples': 1024, 'min_data_in_leaf': 63, 'lambda_l1': 0.0026010488265700554, 'lambda_l2': 0.005827147567076969, 'min_gain_to_split': 0.07374275945345495}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),
[I 2026-04-09 13:24:43,844] Trial 17 finished with value: 0.4045435675650264 and parameters: {'learning_rate': 0.09989174532715045, 'num_leaves': 200, 'max_depth': 37, 'feature_fraction': 0.8864621071645358, 'bagging_fraction': 0.9613989654366141, 'bagging_freq': 17, 'min_child_samples': 1001, 'min_data_in_leaf': 65, 'lambda_l1': 0.0019019213048002003, 'lambda_l2': 0.007997256754336608, 'min_gain_to_split': 0.07996702645560272}. Best is trial 12 with value: 0.4067650391100671.
C:\Users\fchiavassa\AppData\Local\Temp\ipykernel_44164\1189143466.py:27: FutureWarning: suggest_int() got {'step'} as positional arguments but they were expected to be given as keyword arguments.
Positional arguments ['self', 'name', 'low', 'high', 'step', 'log'] in suggest_int() have been deprecated since v3.5.0. They will be replaced with the corresponding keyword arguments in v5.0.0, so please use the keyword specification instead. See https://github.com/optuna/optuna/releases/tag/v3.5.0 for details.
  'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 60, 65, 1),